// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurePoll_BE.Data;

#nullable disable

namespace SecurePoll_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908033352_AddTableElections")]
    partial class AddTableElections
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SecurePoll_BE.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("document_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CC",
                            Name = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "TI",
                            Name = "Tarjeta de Identidad"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PS",
                            Name = "Pasaporte"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "NIT",
                            Name = "Número de Identificación Tributaria"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CE",
                            Name = "Cédula de Extranjería"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "RC",
                            Name = "Registro Civil"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "PEP",
                            Name = "Permiso Especial de Permanencia"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("elections");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Votante"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Candidato"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OauthGoogle")
                        .HasColumnType("longtext")
                        .HasColumnName("oauth_google");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentTypeId = 6,
                            Email = "Rachelle33@hotmail.com",
                            IdentificationNumber = "715853730",
                            LastName = "Breitenberg",
                            Name = "Lelia",
                            OauthGoogle = "Jaclyn.Ullrich",
                            Password = "j9eWiQKoBP",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 2,
                            DocumentTypeId = 1,
                            Email = "Jonatan_McKenzie91@gmail.com",
                            IdentificationNumber = "065099499",
                            LastName = "Breitenberg",
                            Name = "Sabryna",
                            Password = "Js1vAoAXdt",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            DocumentTypeId = 7,
                            Email = "Marcella87@yahoo.com",
                            IdentificationNumber = "635939139",
                            LastName = "Legros",
                            Name = "Danika",
                            OauthGoogle = "Mary75",
                            Password = "u7lpkaEaJ0",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 4,
                            DocumentTypeId = 2,
                            Email = "Wallace.OConnell23@hotmail.com",
                            IdentificationNumber = "595937923",
                            LastName = "Bergstrom",
                            Name = "Pinkie",
                            OauthGoogle = "Antonio.Hilll",
                            Password = "9v5ToMIXqB",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            DocumentTypeId = 4,
                            Email = "Edythe.Strosin87@hotmail.com",
                            IdentificationNumber = "186934588",
                            LastName = "Schuppe",
                            Name = "Francesco",
                            OauthGoogle = "Heber13",
                            Password = "DvQIZUzyrc",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 6,
                            DocumentTypeId = 6,
                            Email = "Marvin_VonRueden41@hotmail.com",
                            IdentificationNumber = "711057528",
                            LastName = "Smitham",
                            Name = "Dallin",
                            Password = "sufrdOTSfw",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            DocumentTypeId = 1,
                            Email = "Estefania.Oberbrunner@yahoo.com",
                            IdentificationNumber = "080106059",
                            LastName = "Kozey",
                            Name = "Athena",
                            OauthGoogle = "Michelle.McClure43",
                            Password = "w8dvKvJc_x",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            DocumentTypeId = 7,
                            Email = "Raleigh.Ruecker68@yahoo.com",
                            IdentificationNumber = "369088617",
                            LastName = "Hartmann",
                            Name = "Oren",
                            Password = "mXmqbZCqag",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            DocumentTypeId = 1,
                            Email = "Amira42@gmail.com",
                            IdentificationNumber = "030512242",
                            LastName = "Stamm",
                            Name = "Kyle",
                            Password = "rWA4j_Rt_j",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 10,
                            DocumentTypeId = 6,
                            Email = "Charity26@yahoo.com",
                            IdentificationNumber = "990735594",
                            LastName = "Oberbrunner",
                            Name = "Ernestine",
                            Password = "56PlEuUebj",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            DocumentTypeId = 7,
                            Email = "Odell91@hotmail.com",
                            IdentificationNumber = "515988603",
                            LastName = "Kunde",
                            Name = "Alexis",
                            OauthGoogle = "Dayna_Bernier",
                            Password = "RxvnnHx3jv",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 12,
                            DocumentTypeId = 7,
                            Email = "Kelsi64@yahoo.com",
                            IdentificationNumber = "551610998",
                            LastName = "Champlin",
                            Name = "Justice",
                            Password = "lQo7v2casD",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            DocumentTypeId = 5,
                            Email = "Furman35@yahoo.com",
                            IdentificationNumber = "977732410",
                            LastName = "Effertz",
                            Name = "Hudson",
                            Password = "y43tzwAYFL",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            DocumentTypeId = 3,
                            Email = "Audrey.Feest@yahoo.com",
                            IdentificationNumber = "460252262",
                            LastName = "Parker",
                            Name = "Armani",
                            Password = "MHHPQH3MKM",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 15,
                            DocumentTypeId = 3,
                            Email = "Antoinette92@yahoo.com",
                            IdentificationNumber = "630691784",
                            LastName = "Willms",
                            Name = "Shane",
                            OauthGoogle = "Adrian.Ferry89",
                            Password = "3e9QIFFbcE",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            DocumentTypeId = 3,
                            Email = "Ofelia.Lockman28@hotmail.com",
                            IdentificationNumber = "526335193",
                            LastName = "Hayes",
                            Name = "Meda",
                            Password = "0dOiBhLQpg",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            DocumentTypeId = 4,
                            Email = "Jennyfer46@yahoo.com",
                            IdentificationNumber = "076330705",
                            LastName = "Stroman",
                            Name = "Cora",
                            Password = "sLusgVlqVf",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 18,
                            DocumentTypeId = 7,
                            Email = "Kennedy.Hilll@yahoo.com",
                            IdentificationNumber = "377746482",
                            LastName = "Luettgen",
                            Name = "Astrid",
                            OauthGoogle = "Gloria_Lubowitz",
                            Password = "JqUQ0epTWA",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            DocumentTypeId = 6,
                            Email = "Xander_Schmitt8@gmail.com",
                            IdentificationNumber = "748006878",
                            LastName = "Harber",
                            Name = "Henriette",
                            Password = "dF0XYiT9OT",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 20,
                            DocumentTypeId = 5,
                            Email = "Alexis_Lueilwitz95@yahoo.com",
                            IdentificationNumber = "465522198",
                            LastName = "Nolan",
                            Name = "Jeramy",
                            Password = "_LoM0B0QYA",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 21,
                            DocumentTypeId = 7,
                            Email = "Name11@yahoo.com",
                            IdentificationNumber = "578417846",
                            LastName = "Kutch",
                            Name = "Trudie",
                            Password = "AF0tU9i5nh",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 22,
                            DocumentTypeId = 4,
                            Email = "Kyra_Schumm18@yahoo.com",
                            IdentificationNumber = "505630537",
                            LastName = "Williamson",
                            Name = "Rahul",
                            OauthGoogle = "Elva_Fahey",
                            Password = "QDmcv6Eixb",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            DocumentTypeId = 3,
                            Email = "Karlie.Schmitt49@yahoo.com",
                            IdentificationNumber = "906070430",
                            LastName = "Ward",
                            Name = "Ericka",
                            Password = "jzOJ0bZW7z",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 24,
                            DocumentTypeId = 6,
                            Email = "Vivian.Bode@gmail.com",
                            IdentificationNumber = "164206501",
                            LastName = "Rodriguez",
                            Name = "Broderick",
                            OauthGoogle = "Keshawn_Osinski47",
                            Password = "xe1EJDtPzi",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 25,
                            DocumentTypeId = 7,
                            Email = "Lia.Erdman@gmail.com",
                            IdentificationNumber = "990076881",
                            LastName = "Howell",
                            Name = "Roselyn",
                            Password = "Ufo_RloheN",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 26,
                            DocumentTypeId = 5,
                            Email = "Marlen55@yahoo.com",
                            IdentificationNumber = "953491615",
                            LastName = "Dicki",
                            Name = "Santiago",
                            Password = "m7msZH_8J_",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 27,
                            DocumentTypeId = 1,
                            Email = "Warren9@hotmail.com",
                            IdentificationNumber = "905709832",
                            LastName = "Hane",
                            Name = "Emilie",
                            Password = "TTM0J3w1Bc",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 28,
                            DocumentTypeId = 1,
                            Email = "Alfredo.Hettinger86@hotmail.com",
                            IdentificationNumber = "061099520",
                            LastName = "Wisozk",
                            Name = "Ophelia",
                            Password = "44DR0SnDTe",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 29,
                            DocumentTypeId = 2,
                            Email = "Kyra_Dickens@gmail.com",
                            IdentificationNumber = "457898340",
                            LastName = "Schneider",
                            Name = "Lillie",
                            OauthGoogle = "Chet.Bashirian",
                            Password = "a_bmBMmRoJ",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            DocumentTypeId = 2,
                            Email = "Amina.Zboncak@gmail.com",
                            IdentificationNumber = "650483541",
                            LastName = "Witting",
                            Name = "Cale",
                            OauthGoogle = "Macie.Wisoky47",
                            Password = "cRuXDG19gs",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            DocumentTypeId = 6,
                            Email = "Andreane_Feest@hotmail.com",
                            IdentificationNumber = "554468391",
                            LastName = "Howell",
                            Name = "Delphine",
                            Password = "4cMcaObuGq",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            DocumentTypeId = 6,
                            Email = "Chester_Kessler@gmail.com",
                            IdentificationNumber = "226568027",
                            LastName = "Rogahn",
                            Name = "Mariela",
                            Password = "aPReJXwpJB",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            DocumentTypeId = 1,
                            Email = "Opal.Howell@hotmail.com",
                            IdentificationNumber = "285067914",
                            LastName = "Buckridge",
                            Name = "Libby",
                            OauthGoogle = "Drake.Bailey",
                            Password = "W90_0zi2Z9",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 34,
                            DocumentTypeId = 5,
                            Email = "Aileen.Dooley85@gmail.com",
                            IdentificationNumber = "666073334",
                            LastName = "Kassulke",
                            Name = "Aylin",
                            OauthGoogle = "Eunice_Hand53",
                            Password = "gaYCEE3d1K",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 35,
                            DocumentTypeId = 6,
                            Email = "Petra8@yahoo.com",
                            IdentificationNumber = "962789279",
                            LastName = "Ferry",
                            Name = "Alanis",
                            OauthGoogle = "Makenzie_Stamm57",
                            Password = "oxg6rlzklJ",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            DocumentTypeId = 3,
                            Email = "Clifford_Beer@hotmail.com",
                            IdentificationNumber = "736140594",
                            LastName = "Rath",
                            Name = "Mervin",
                            Password = "6w2HritmQI",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 37,
                            DocumentTypeId = 5,
                            Email = "Devonte_Schaden94@gmail.com",
                            IdentificationNumber = "199444014",
                            LastName = "Collins",
                            Name = "Leo",
                            Password = "NnFyvs09C9",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 38,
                            DocumentTypeId = 4,
                            Email = "Grayson.Schimmel@yahoo.com",
                            IdentificationNumber = "352138109",
                            LastName = "Schaden",
                            Name = "Giuseppe",
                            Password = "bEswfSS7GL",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            DocumentTypeId = 5,
                            Email = "Crystel93@gmail.com",
                            IdentificationNumber = "846405424",
                            LastName = "Friesen",
                            Name = "Kyleigh",
                            OauthGoogle = "Leilani.Cole",
                            Password = "j836dOx0Z_",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 40,
                            DocumentTypeId = 6,
                            Email = "Abby.Buckridge@hotmail.com",
                            IdentificationNumber = "766065553",
                            LastName = "Spencer",
                            Name = "Leopold",
                            OauthGoogle = "Rowland59",
                            Password = "5CurRZpKX3",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 41,
                            DocumentTypeId = 5,
                            Email = "Claud_Murazik@gmail.com",
                            IdentificationNumber = "123027761",
                            LastName = "Pfannerstill",
                            Name = "Markus",
                            OauthGoogle = "Sim.Gaylord29",
                            Password = "PGne4SKDRh",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 42,
                            DocumentTypeId = 4,
                            Email = "Laurence74@yahoo.com",
                            IdentificationNumber = "593729447",
                            LastName = "Nicolas",
                            Name = "Jameson",
                            Password = "6_1QO0tE8r",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 43,
                            DocumentTypeId = 2,
                            Email = "Jeffery_Waelchi@yahoo.com",
                            IdentificationNumber = "013251062",
                            LastName = "Schmidt",
                            Name = "Tierra",
                            OauthGoogle = "Freida.Pfeffer",
                            Password = "qXq1hxqbaC",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 44,
                            DocumentTypeId = 2,
                            Email = "Albert.Will4@hotmail.com",
                            IdentificationNumber = "508410799",
                            LastName = "Bayer",
                            Name = "Johnnie",
                            Password = "dPcSyooq0P",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 45,
                            DocumentTypeId = 5,
                            Email = "Madge28@yahoo.com",
                            IdentificationNumber = "565272903",
                            LastName = "Moore",
                            Name = "Lazaro",
                            Password = "yJf2aUOnYz",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            DocumentTypeId = 2,
                            Email = "Kathryne.Ledner@gmail.com",
                            IdentificationNumber = "009207131",
                            LastName = "Jacobson",
                            Name = "Cortney",
                            Password = "pXiOOyAzOr",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 47,
                            DocumentTypeId = 3,
                            Email = "Eliza_Runolfsson2@yahoo.com",
                            IdentificationNumber = "365203217",
                            LastName = "Cartwright",
                            Name = "Veda",
                            Password = "ZFWw1b7SR7",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 48,
                            DocumentTypeId = 2,
                            Email = "Angela51@gmail.com",
                            IdentificationNumber = "608168184",
                            LastName = "Gulgowski",
                            Name = "Mavis",
                            OauthGoogle = "Jaycee.Bernier",
                            Password = "3qgd0tRnnL",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 49,
                            DocumentTypeId = 3,
                            Email = "Daniela.Stoltenberg@gmail.com",
                            IdentificationNumber = "398495438",
                            LastName = "Schuppe",
                            Name = "Janae",
                            Password = "2uMdxRDXLy",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 50,
                            DocumentTypeId = 6,
                            Email = "Eda_Kihn@hotmail.com",
                            IdentificationNumber = "379729624",
                            LastName = "Wunsch",
                            Name = "Cecil",
                            Password = "v4CspFKUf_",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 51,
                            DocumentTypeId = 1,
                            Email = "Jennifer2@gmail.com",
                            IdentificationNumber = "345590159",
                            LastName = "Corwin",
                            Name = "Dylan",
                            OauthGoogle = "Will_Greenholt98",
                            Password = "vlAyxsXcpa",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 52,
                            DocumentTypeId = 6,
                            Email = "Adelle90@gmail.com",
                            IdentificationNumber = "354054096",
                            LastName = "Jacobi",
                            Name = "Garth",
                            Password = "BlV0D8VskI",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 53,
                            DocumentTypeId = 6,
                            Email = "Dedrick53@yahoo.com",
                            IdentificationNumber = "089443014",
                            LastName = "Ferry",
                            Name = "Scot",
                            OauthGoogle = "Keeley39",
                            Password = "lXqVexQc9F",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            DocumentTypeId = 1,
                            Email = "Eliza.Schumm43@yahoo.com",
                            IdentificationNumber = "631995040",
                            LastName = "Willms",
                            Name = "Germaine",
                            Password = "IMKDF7RiXZ",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 55,
                            DocumentTypeId = 6,
                            Email = "Marjolaine_Denesik98@hotmail.com",
                            IdentificationNumber = "921153563",
                            LastName = "Mann",
                            Name = "Marianne",
                            Password = "osNF3X5MeA",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 56,
                            DocumentTypeId = 7,
                            Email = "Kayden76@yahoo.com",
                            IdentificationNumber = "526574273",
                            LastName = "Ortiz",
                            Name = "Jasmin",
                            Password = "fTj9jzXykA",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 57,
                            DocumentTypeId = 6,
                            Email = "Patience55@gmail.com",
                            IdentificationNumber = "246847162",
                            LastName = "Weimann",
                            Name = "Haley",
                            Password = "A53lsIZuNh",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 58,
                            DocumentTypeId = 7,
                            Email = "Herman.Reichel@yahoo.com",
                            IdentificationNumber = "468356119",
                            LastName = "Leuschke",
                            Name = "Kane",
                            Password = "BdgiXNWtBd",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 59,
                            DocumentTypeId = 4,
                            Email = "Dana_Goldner@yahoo.com",
                            IdentificationNumber = "785860956",
                            LastName = "O'Keefe",
                            Name = "Dennis",
                            Password = "DqYk5J8AlS",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 60,
                            DocumentTypeId = 7,
                            Email = "Lucie.Zulauf59@yahoo.com",
                            IdentificationNumber = "242069377",
                            LastName = "Johns",
                            Name = "April",
                            OauthGoogle = "Myrtie12",
                            Password = "QceXtZexKp",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 61,
                            DocumentTypeId = 6,
                            Email = "Ella31@hotmail.com",
                            IdentificationNumber = "926591878",
                            LastName = "Hansen",
                            Name = "Lindsey",
                            Password = "w_Kjuur5O1",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 62,
                            DocumentTypeId = 4,
                            Email = "Mertie_Stoltenberg73@gmail.com",
                            IdentificationNumber = "763999707",
                            LastName = "Bruen",
                            Name = "Arch",
                            Password = "AxowQq34S3",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 63,
                            DocumentTypeId = 5,
                            Email = "Filomena.Pfeffer34@yahoo.com",
                            IdentificationNumber = "731951760",
                            LastName = "Lang",
                            Name = "Kenny",
                            Password = "RH8TIaGvwb",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 64,
                            DocumentTypeId = 5,
                            Email = "Devyn.Schoen@hotmail.com",
                            IdentificationNumber = "176987421",
                            LastName = "Wilderman",
                            Name = "Carolyn",
                            Password = "vqqomSiu_R",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 65,
                            DocumentTypeId = 4,
                            Email = "Rosendo_Goldner43@gmail.com",
                            IdentificationNumber = "646300762",
                            LastName = "Cummings",
                            Name = "Justine",
                            OauthGoogle = "Reta82",
                            Password = "aWTwj_oLGW",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 66,
                            DocumentTypeId = 2,
                            Email = "Eugene92@gmail.com",
                            IdentificationNumber = "373370964",
                            LastName = "Shields",
                            Name = "Mia",
                            OauthGoogle = "Yvonne_Graham",
                            Password = "nk5ExS8wsZ",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 67,
                            DocumentTypeId = 5,
                            Email = "Nora10@hotmail.com",
                            IdentificationNumber = "922547143",
                            LastName = "Russel",
                            Name = "Libby",
                            OauthGoogle = "Kaleigh.Roberts68",
                            Password = "MkhfYZW91R",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 68,
                            DocumentTypeId = 5,
                            Email = "Gaston_Kirlin@yahoo.com",
                            IdentificationNumber = "301146767",
                            LastName = "Smith",
                            Name = "Edwin",
                            OauthGoogle = "Wilton.Gulgowski",
                            Password = "JxSKsOt1f_",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 69,
                            DocumentTypeId = 2,
                            Email = "Carmine_Cormier1@gmail.com",
                            IdentificationNumber = "427671697",
                            LastName = "Rempel",
                            Name = "Juana",
                            Password = "zTbuf4R9s0",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 70,
                            DocumentTypeId = 3,
                            Email = "Kory48@yahoo.com",
                            IdentificationNumber = "721528089",
                            LastName = "Reichert",
                            Name = "Lia",
                            OauthGoogle = "Kadin.Sauer50",
                            Password = "GRGwN0ADQ_",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 71,
                            DocumentTypeId = 1,
                            Email = "Noemi.Roberts72@hotmail.com",
                            IdentificationNumber = "186385219",
                            LastName = "Russel",
                            Name = "Jane",
                            OauthGoogle = "Soledad.Dickinson2",
                            Password = "JSVhw0uJrW",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 72,
                            DocumentTypeId = 2,
                            Email = "Bernard71@yahoo.com",
                            IdentificationNumber = "567599231",
                            LastName = "Orn",
                            Name = "Lucie",
                            Password = "rg31fmY0KI",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 73,
                            DocumentTypeId = 6,
                            Email = "Maya54@gmail.com",
                            IdentificationNumber = "533215857",
                            LastName = "Ziemann",
                            Name = "Ursula",
                            Password = "n6uwVLJrdG",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 74,
                            DocumentTypeId = 2,
                            Email = "Nicholas12@hotmail.com",
                            IdentificationNumber = "931215244",
                            LastName = "Nitzsche",
                            Name = "Hayley",
                            OauthGoogle = "Margarete39",
                            Password = "0A9xTFXCvj",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 75,
                            DocumentTypeId = 1,
                            Email = "Hannah.Feest77@hotmail.com",
                            IdentificationNumber = "068960475",
                            LastName = "Dibbert",
                            Name = "Jabari",
                            OauthGoogle = "Garrison_Wilkinson",
                            Password = "hNPOOZ3lKd",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 76,
                            DocumentTypeId = 1,
                            Email = "Katelynn_Romaguera75@hotmail.com",
                            IdentificationNumber = "022651879",
                            LastName = "Hahn",
                            Name = "Vince",
                            Password = "4KaCCf8D_8",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 77,
                            DocumentTypeId = 6,
                            Email = "Sanford.McDermott62@gmail.com",
                            IdentificationNumber = "249692159",
                            LastName = "Kreiger",
                            Name = "Alexandre",
                            OauthGoogle = "Darron.Cummerata85",
                            Password = "IeYh6tvBYw",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 78,
                            DocumentTypeId = 3,
                            Email = "Josiah_Kihn70@hotmail.com",
                            IdentificationNumber = "307611078",
                            LastName = "Koss",
                            Name = "Zaria",
                            Password = "SxDVirCebK",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 79,
                            DocumentTypeId = 2,
                            Email = "Kiel.Koelpin@gmail.com",
                            IdentificationNumber = "766959398",
                            LastName = "Harris",
                            Name = "Jacinto",
                            OauthGoogle = "Sabina_Anderson31",
                            Password = "zKDtUuBxFD",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 80,
                            DocumentTypeId = 7,
                            Email = "Rahsaan.Kunde90@hotmail.com",
                            IdentificationNumber = "267270544",
                            LastName = "Hirthe",
                            Name = "Marcus",
                            Password = "rqdWeTaEvp",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 81,
                            DocumentTypeId = 3,
                            Email = "Karson60@gmail.com",
                            IdentificationNumber = "199423753",
                            LastName = "Monahan",
                            Name = "Reece",
                            OauthGoogle = "Laisha47",
                            Password = "PkjoX4g2rv",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 82,
                            DocumentTypeId = 2,
                            Email = "Precious_Kub@gmail.com",
                            IdentificationNumber = "176696496",
                            LastName = "Fadel",
                            Name = "Mikayla",
                            OauthGoogle = "Sydnie.Lemke92",
                            Password = "IjGEiJ0Xu6",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 83,
                            DocumentTypeId = 2,
                            Email = "Mallie.Labadie83@hotmail.com",
                            IdentificationNumber = "497426795",
                            LastName = "Thompson",
                            Name = "Corbin",
                            OauthGoogle = "Orie61",
                            Password = "4wINKrGnXW",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 84,
                            DocumentTypeId = 4,
                            Email = "Idell_Lind@hotmail.com",
                            IdentificationNumber = "575526022",
                            LastName = "Harvey",
                            Name = "Emelia",
                            Password = "n5GPc31D0Q",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 85,
                            DocumentTypeId = 7,
                            Email = "Piper61@hotmail.com",
                            IdentificationNumber = "111977358",
                            LastName = "Rogahn",
                            Name = "Deontae",
                            OauthGoogle = "Earnest_Gibson",
                            Password = "zFGpRR5fxp",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 86,
                            DocumentTypeId = 4,
                            Email = "Alf_Kunze@hotmail.com",
                            IdentificationNumber = "602792185",
                            LastName = "Conroy",
                            Name = "Ralph",
                            Password = "RMlG_mYrJH",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 87,
                            DocumentTypeId = 4,
                            Email = "Ayden.Zemlak@hotmail.com",
                            IdentificationNumber = "892262148",
                            LastName = "Glover",
                            Name = "Devante",
                            Password = "O0YseEh_MU",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 88,
                            DocumentTypeId = 2,
                            Email = "Federico.Okuneva27@yahoo.com",
                            IdentificationNumber = "095893547",
                            LastName = "Ankunding",
                            Name = "Tressie",
                            OauthGoogle = "Cristian_Deckow89",
                            Password = "Je8CFY3sbC",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 89,
                            DocumentTypeId = 1,
                            Email = "Pearl_Wunsch@hotmail.com",
                            IdentificationNumber = "336984880",
                            LastName = "Collier",
                            Name = "Vidal",
                            OauthGoogle = "Edwina_Osinski",
                            Password = "yvuw6vVL7K",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 90,
                            DocumentTypeId = 2,
                            Email = "Dortha.Orn@gmail.com",
                            IdentificationNumber = "885408490",
                            LastName = "Hegmann",
                            Name = "Meda",
                            Password = "RpVRpvKth7",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 91,
                            DocumentTypeId = 2,
                            Email = "Yadira_Goodwin@yahoo.com",
                            IdentificationNumber = "329442057",
                            LastName = "Emard",
                            Name = "Royal",
                            OauthGoogle = "Mary.Mertz",
                            Password = "9pkvbDSsWu",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 92,
                            DocumentTypeId = 7,
                            Email = "Dayna95@hotmail.com",
                            IdentificationNumber = "762058977",
                            LastName = "Friesen",
                            Name = "Irma",
                            Password = "D5qbp1jQAH",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 93,
                            DocumentTypeId = 4,
                            Email = "Marquis99@gmail.com",
                            IdentificationNumber = "950372731",
                            LastName = "Moore",
                            Name = "Richard",
                            Password = "UXWcJYIWI_",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 94,
                            DocumentTypeId = 6,
                            Email = "Delilah93@hotmail.com",
                            IdentificationNumber = "911527027",
                            LastName = "Raynor",
                            Name = "Yadira",
                            OauthGoogle = "Elisa.Grimes91",
                            Password = "dw8SjyLE7L",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 95,
                            DocumentTypeId = 2,
                            Email = "Erwin.Morar@yahoo.com",
                            IdentificationNumber = "392526646",
                            LastName = "Schroeder",
                            Name = "Maymie",
                            Password = "Oo_PdqyowP",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 96,
                            DocumentTypeId = 2,
                            Email = "Dovie_Berge@hotmail.com",
                            IdentificationNumber = "906637883",
                            LastName = "MacGyver",
                            Name = "Fausto",
                            OauthGoogle = "Rosalind_Macejkovic",
                            Password = "w_TdbZD9nq",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 97,
                            DocumentTypeId = 6,
                            Email = "Ansley55@yahoo.com",
                            IdentificationNumber = "806836860",
                            LastName = "Tromp",
                            Name = "Phoebe",
                            OauthGoogle = "Adrain_Gleichner67",
                            Password = "djMii43QAJ",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 98,
                            DocumentTypeId = 2,
                            Email = "Geovanni_Abshire@gmail.com",
                            IdentificationNumber = "048543306",
                            LastName = "Gaylord",
                            Name = "Keira",
                            OauthGoogle = "Hilbert19",
                            Password = "RbN7y5WA_6",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 99,
                            DocumentTypeId = 3,
                            Email = "Zaria91@hotmail.com",
                            IdentificationNumber = "236379958",
                            LastName = "Grimes",
                            Name = "Sabryna",
                            OauthGoogle = "Summer.Murphy",
                            Password = "Pt8G_Fd4q_",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 100,
                            DocumentTypeId = 2,
                            Email = "Olaf85@yahoo.com",
                            IdentificationNumber = "489260627",
                            LastName = "Runte",
                            Name = "Leonardo",
                            Password = "pcP9QjiGIB",
                            RoleId = 4
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.Rol", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
