// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurePoll_BE.Data;

#nullable disable

namespace SecurePoll_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908032458_SeedUsersWithBogus")]
    partial class SeedUsersWithBogus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SecurePoll_BE.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("document_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CC",
                            Name = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "TI",
                            Name = "Tarjeta de Identidad"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PS",
                            Name = "Pasaporte"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "NIT",
                            Name = "Número de Identificación Tributaria"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CE",
                            Name = "Cédula de Extranjería"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "RC",
                            Name = "Registro Civil"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "PEP",
                            Name = "Permiso Especial de Permanencia"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Votante"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Candidato"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OauthGoogle")
                        .HasColumnType("longtext")
                        .HasColumnName("oauth_google");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentTypeId = 7,
                            Email = "Adolf_Shanahan@yahoo.com",
                            IdentificationNumber = "925139522",
                            LastName = "Deckow",
                            Name = "Muhammad",
                            OauthGoogle = "Sydnie.Kuvalis63",
                            Password = "2TSeBOVHpu",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            DocumentTypeId = 1,
                            Email = "Cullen_Batz70@yahoo.com",
                            IdentificationNumber = "799881569",
                            LastName = "Dickens",
                            Name = "Elaina",
                            Password = "L8hMWPLa31",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            DocumentTypeId = 5,
                            Email = "Mustafa.Metz@gmail.com",
                            IdentificationNumber = "078203246",
                            LastName = "Green",
                            Name = "Myrna",
                            OauthGoogle = "Patsy.Reilly",
                            Password = "2_qXzUalmG",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 4,
                            DocumentTypeId = 5,
                            Email = "Gloria_Reinger33@hotmail.com",
                            IdentificationNumber = "261650713",
                            LastName = "Oberbrunner",
                            Name = "Genevieve",
                            OauthGoogle = "Weston.Bode",
                            Password = "1LsZInFH5X",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            DocumentTypeId = 2,
                            Email = "Evie91@yahoo.com",
                            IdentificationNumber = "792382682",
                            LastName = "Smith",
                            Name = "Maxwell",
                            OauthGoogle = "Ismael97",
                            Password = "5FGILiCx6C",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 6,
                            DocumentTypeId = 7,
                            Email = "Letitia_Padberg76@yahoo.com",
                            IdentificationNumber = "176674915",
                            LastName = "Bartoletti",
                            Name = "Desiree",
                            Password = "E4mDaYsMsc",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            DocumentTypeId = 2,
                            Email = "Norris_Zieme@hotmail.com",
                            IdentificationNumber = "214191679",
                            LastName = "Lueilwitz",
                            Name = "Beth",
                            OauthGoogle = "Alden40",
                            Password = "ciDW5Ub7o7",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            DocumentTypeId = 7,
                            Email = "Kaitlin.Lemke@hotmail.com",
                            IdentificationNumber = "137320966",
                            LastName = "Koepp",
                            Name = "Anastacio",
                            Password = "_qZ11mUDtH",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 9,
                            DocumentTypeId = 6,
                            Email = "Damian_Gerlach89@hotmail.com",
                            IdentificationNumber = "403221265",
                            LastName = "Fritsch",
                            Name = "Madeline",
                            OauthGoogle = "Jude66",
                            Password = "1TwenccyVW",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 10,
                            DocumentTypeId = 2,
                            Email = "Carissa98@hotmail.com",
                            IdentificationNumber = "663109671",
                            LastName = "Krajcik",
                            Name = "Camilla",
                            Password = "zOwti66ctH",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 11,
                            DocumentTypeId = 5,
                            Email = "Cleora67@yahoo.com",
                            IdentificationNumber = "439070940",
                            LastName = "Glover",
                            Name = "Geo",
                            OauthGoogle = "Beaulah50",
                            Password = "bsyXNx08Sh",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            DocumentTypeId = 1,
                            Email = "Destin.Fritsch99@hotmail.com",
                            IdentificationNumber = "548557003",
                            LastName = "Reichert",
                            Name = "Alf",
                            Password = "8Bl6KHd3ud",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            DocumentTypeId = 3,
                            Email = "Patsy.Walsh@gmail.com",
                            IdentificationNumber = "704069577",
                            LastName = "Botsford",
                            Name = "Deshaun",
                            Password = "QEmRADtNa2",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 14,
                            DocumentTypeId = 5,
                            Email = "Dee.OKon26@hotmail.com",
                            IdentificationNumber = "954799228",
                            LastName = "Gaylord",
                            Name = "Raymond",
                            Password = "IhJjJcNbep",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 15,
                            DocumentTypeId = 3,
                            Email = "Hermina91@hotmail.com",
                            IdentificationNumber = "705478814",
                            LastName = "Wiza",
                            Name = "Frances",
                            OauthGoogle = "Davonte7",
                            Password = "PuEaTv4sZz",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 16,
                            DocumentTypeId = 3,
                            Email = "Johathan58@hotmail.com",
                            IdentificationNumber = "605947461",
                            LastName = "Gleichner",
                            Name = "Patrick",
                            OauthGoogle = "Judd_Funk",
                            Password = "BFy3Y3N1We",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            DocumentTypeId = 4,
                            Email = "Beaulah.Ratke@yahoo.com",
                            IdentificationNumber = "535369155",
                            LastName = "Yost",
                            Name = "Jedediah",
                            OauthGoogle = "Jerald_Fay56",
                            Password = "ze8ObRUL7M",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            DocumentTypeId = 5,
                            Email = "Amina_Haley83@yahoo.com",
                            IdentificationNumber = "127713960",
                            LastName = "Ebert",
                            Name = "Florine",
                            OauthGoogle = "Tyrese93",
                            Password = "jOQ5kQOF1q",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            DocumentTypeId = 4,
                            Email = "Zelda.Pfeffer5@hotmail.com",
                            IdentificationNumber = "841613964",
                            LastName = "Larson",
                            Name = "Mohamed",
                            Password = "n4JdNnHUoK",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 20,
                            DocumentTypeId = 4,
                            Email = "Constantin19@gmail.com",
                            IdentificationNumber = "692021107",
                            LastName = "Hickle",
                            Name = "Magali",
                            OauthGoogle = "Jamal50",
                            Password = "Py9DVQsS51",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            DocumentTypeId = 5,
                            Email = "Stacey43@hotmail.com",
                            IdentificationNumber = "007190606",
                            LastName = "Wolf",
                            Name = "Joe",
                            Password = "gpX0rIPxaF",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 22,
                            DocumentTypeId = 4,
                            Email = "Dejon.Weissnat79@yahoo.com",
                            IdentificationNumber = "253089238",
                            LastName = "Oberbrunner",
                            Name = "Jason",
                            OauthGoogle = "Ericka_Turner67",
                            Password = "sEKlOMxqN4",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 23,
                            DocumentTypeId = 3,
                            Email = "Marquis2@gmail.com",
                            IdentificationNumber = "228765665",
                            LastName = "Larson",
                            Name = "Laurine",
                            Password = "1Miiv3DnBT",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            DocumentTypeId = 4,
                            Email = "Lulu.Bosco@hotmail.com",
                            IdentificationNumber = "109673216",
                            LastName = "Stanton",
                            Name = "Joshuah",
                            Password = "N1gzqJ_DHy",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 25,
                            DocumentTypeId = 2,
                            Email = "Maximillia.Wisoky51@gmail.com",
                            IdentificationNumber = "734367722",
                            LastName = "Langworth",
                            Name = "Samir",
                            Password = "4NxgGgSp42",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 26,
                            DocumentTypeId = 7,
                            Email = "Mandy80@yahoo.com",
                            IdentificationNumber = "392489396",
                            LastName = "Mann",
                            Name = "Garrett",
                            Password = "3teT2Cbkj8",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 27,
                            DocumentTypeId = 7,
                            Email = "Robb.Veum25@hotmail.com",
                            IdentificationNumber = "397235061",
                            LastName = "Reichel",
                            Name = "Bartholome",
                            Password = "XEdN96jy8b",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 28,
                            DocumentTypeId = 7,
                            Email = "Giovanna_OConner@yahoo.com",
                            IdentificationNumber = "206573449",
                            LastName = "Johnson",
                            Name = "Felton",
                            OauthGoogle = "Lucious_Steuber",
                            Password = "tWf7t3iUNV",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 29,
                            DocumentTypeId = 5,
                            Email = "Gunnar64@yahoo.com",
                            IdentificationNumber = "740874930",
                            LastName = "Ferry",
                            Name = "Lauretta",
                            OauthGoogle = "Garth_Hansen41",
                            Password = "uQwRcJiYZo",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 30,
                            DocumentTypeId = 3,
                            Email = "Aidan_McDermott33@hotmail.com",
                            IdentificationNumber = "349797731",
                            LastName = "Lockman",
                            Name = "Lenore",
                            Password = "F_HHijCS8B",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 31,
                            DocumentTypeId = 6,
                            Email = "Hoyt_Grimes49@yahoo.com",
                            IdentificationNumber = "934158602",
                            LastName = "Franecki",
                            Name = "George",
                            Password = "UtjlKUNFs_",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 32,
                            DocumentTypeId = 6,
                            Email = "Connie.Hartmann@hotmail.com",
                            IdentificationNumber = "239760050",
                            LastName = "Leannon",
                            Name = "Sherwood",
                            OauthGoogle = "Jessica_Ratke",
                            Password = "M7lLnS7hGD",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 33,
                            DocumentTypeId = 4,
                            Email = "Christina86@hotmail.com",
                            IdentificationNumber = "183105228",
                            LastName = "Schamberger",
                            Name = "Lura",
                            Password = "HWQPS4r6QE",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            DocumentTypeId = 1,
                            Email = "Lucinda99@hotmail.com",
                            IdentificationNumber = "634736338",
                            LastName = "Heaney",
                            Name = "Clair",
                            OauthGoogle = "Kelsi.Pouros59",
                            Password = "IinoyNylJg",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 35,
                            DocumentTypeId = 6,
                            Email = "Dena_Hoeger37@hotmail.com",
                            IdentificationNumber = "531471693",
                            LastName = "Predovic",
                            Name = "Isom",
                            OauthGoogle = "Patsy.Parisian34",
                            Password = "YGo9q9qe5C",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 36,
                            DocumentTypeId = 3,
                            Email = "Clement_Grimes27@gmail.com",
                            IdentificationNumber = "182176486",
                            LastName = "Batz",
                            Name = "Isaac",
                            Password = "jDXDF0Y72G",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 37,
                            DocumentTypeId = 1,
                            Email = "Jadon.Streich@hotmail.com",
                            IdentificationNumber = "193863843",
                            LastName = "Stehr",
                            Name = "Keven",
                            OauthGoogle = "Celine_Cormier49",
                            Password = "qPh1donEZf",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 38,
                            DocumentTypeId = 7,
                            Email = "Electa_Kulas@yahoo.com",
                            IdentificationNumber = "730499113",
                            LastName = "Homenick",
                            Name = "Myriam",
                            Password = "qiKcOrNUyL",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 39,
                            DocumentTypeId = 4,
                            Email = "Kurt21@yahoo.com",
                            IdentificationNumber = "354013526",
                            LastName = "Trantow",
                            Name = "Rickey",
                            Password = "fkxB24_5g7",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 40,
                            DocumentTypeId = 6,
                            Email = "Edgardo_Borer50@hotmail.com",
                            IdentificationNumber = "104196641",
                            LastName = "Auer",
                            Name = "Sierra",
                            OauthGoogle = "Alfred.Leuschke",
                            Password = "JBiJzZzRI7",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            DocumentTypeId = 4,
                            Email = "Quentin_Bartoletti@gmail.com",
                            IdentificationNumber = "889075280",
                            LastName = "Kilback",
                            Name = "Marquis",
                            Password = "EtZpl2xI7g",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 42,
                            DocumentTypeId = 5,
                            Email = "Kenya.Jakubowski25@gmail.com",
                            IdentificationNumber = "591877560",
                            LastName = "Rowe",
                            Name = "Kris",
                            Password = "tQoYIyJ08_",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 43,
                            DocumentTypeId = 5,
                            Email = "Oscar_Kuvalis48@gmail.com",
                            IdentificationNumber = "908110841",
                            LastName = "Windler",
                            Name = "Adrien",
                            OauthGoogle = "Johnpaul.Muller47",
                            Password = "p2R9yNmgp0",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 44,
                            DocumentTypeId = 2,
                            Email = "Juvenal.Lehner@gmail.com",
                            IdentificationNumber = "686969799",
                            LastName = "Kuvalis",
                            Name = "Crawford",
                            Password = "NXwsO0rTBE",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            DocumentTypeId = 6,
                            Email = "Einar.Purdy@hotmail.com",
                            IdentificationNumber = "877623946",
                            LastName = "Bode",
                            Name = "Berniece",
                            Password = "Zt3g5a9Zw3",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            DocumentTypeId = 4,
                            Email = "Oda43@hotmail.com",
                            IdentificationNumber = "167160546",
                            LastName = "Hahn",
                            Name = "Colten",
                            Password = "fQOZzrK2e0",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 47,
                            DocumentTypeId = 1,
                            Email = "Zaria.Von28@hotmail.com",
                            IdentificationNumber = "619718410",
                            LastName = "Nitzsche",
                            Name = "Mireya",
                            OauthGoogle = "Liliane72",
                            Password = "fR8Yis29ZH",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 48,
                            DocumentTypeId = 7,
                            Email = "Dominique81@gmail.com",
                            IdentificationNumber = "595697141",
                            LastName = "Grimes",
                            Name = "Nelson",
                            OauthGoogle = "Clay64",
                            Password = "tZmlFknui_",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 49,
                            DocumentTypeId = 5,
                            Email = "Gino_Homenick@yahoo.com",
                            IdentificationNumber = "845703403",
                            LastName = "Pfannerstill",
                            Name = "Electa",
                            OauthGoogle = "Fred94",
                            Password = "XicxfoUMn_",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 50,
                            DocumentTypeId = 1,
                            Email = "Misael97@gmail.com",
                            IdentificationNumber = "775288086",
                            LastName = "O'Kon",
                            Name = "Dovie",
                            Password = "BK246q5agF",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            DocumentTypeId = 6,
                            Email = "Omari41@hotmail.com",
                            IdentificationNumber = "586563104",
                            LastName = "Jerde",
                            Name = "Carolyn",
                            Password = "nx0GXR53Zo",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 52,
                            DocumentTypeId = 7,
                            Email = "Mariela_Johns85@yahoo.com",
                            IdentificationNumber = "487023908",
                            LastName = "Gorczany",
                            Name = "Dovie",
                            Password = "OQzprCcNYv",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 53,
                            DocumentTypeId = 1,
                            Email = "Deion.Grant@hotmail.com",
                            IdentificationNumber = "245016421",
                            LastName = "Boyer",
                            Name = "Ilene",
                            OauthGoogle = "Miracle82",
                            Password = "y7mtlWrImd",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 54,
                            DocumentTypeId = 4,
                            Email = "Nicklaus.Pacocha@hotmail.com",
                            IdentificationNumber = "870161033",
                            LastName = "Tillman",
                            Name = "Donnie",
                            OauthGoogle = "Kailee.Muller47",
                            Password = "loPnCOHDc1",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 55,
                            DocumentTypeId = 1,
                            Email = "Krystel18@gmail.com",
                            IdentificationNumber = "964429439",
                            LastName = "O'Connell",
                            Name = "Ciara",
                            Password = "hUggLxr5iH",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 56,
                            DocumentTypeId = 4,
                            Email = "Felipe_Hodkiewicz62@hotmail.com",
                            IdentificationNumber = "736345989",
                            LastName = "Dicki",
                            Name = "Quentin",
                            Password = "I2p2qnT9g_",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 57,
                            DocumentTypeId = 3,
                            Email = "Tod_Cassin@hotmail.com",
                            IdentificationNumber = "879848182",
                            LastName = "Keebler",
                            Name = "Keshawn",
                            OauthGoogle = "Reinhold.Romaguera",
                            Password = "P_oTDE0zWj",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 58,
                            DocumentTypeId = 1,
                            Email = "Alexandra.Bauch@gmail.com",
                            IdentificationNumber = "080576463",
                            LastName = "Hermiston",
                            Name = "Brenden",
                            OauthGoogle = "Donny_Weber",
                            Password = "r2RKjiUMaS",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 59,
                            DocumentTypeId = 3,
                            Email = "Rupert_Bartoletti28@yahoo.com",
                            IdentificationNumber = "083023451",
                            LastName = "Effertz",
                            Name = "Jaren",
                            OauthGoogle = "Duncan.Zboncak",
                            Password = "bneEy5P1rM",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 60,
                            DocumentTypeId = 3,
                            Email = "Malachi_Dickinson87@gmail.com",
                            IdentificationNumber = "762550834",
                            LastName = "Hickle",
                            Name = "Kelley",
                            OauthGoogle = "Winfield_Zieme",
                            Password = "hHlMu13Hhy",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 61,
                            DocumentTypeId = 1,
                            Email = "Alanna.Greenfelder@yahoo.com",
                            IdentificationNumber = "219652433",
                            LastName = "Langosh",
                            Name = "Candida",
                            OauthGoogle = "Kendra.Daugherty",
                            Password = "Umb58q5sbK",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 62,
                            DocumentTypeId = 5,
                            Email = "Elena80@gmail.com",
                            IdentificationNumber = "719008521",
                            LastName = "Stamm",
                            Name = "Eladio",
                            OauthGoogle = "Mack_Kuphal",
                            Password = "YYD3qEv8eu",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 63,
                            DocumentTypeId = 3,
                            Email = "Jerald57@hotmail.com",
                            IdentificationNumber = "638783975",
                            LastName = "Heidenreich",
                            Name = "Austyn",
                            Password = "MQmRlKIPga",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 64,
                            DocumentTypeId = 7,
                            Email = "Henderson42@gmail.com",
                            IdentificationNumber = "672883798",
                            LastName = "Witting",
                            Name = "Margarita",
                            OauthGoogle = "Maximilian.Lakin",
                            Password = "q5L8u4r_KX",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 65,
                            DocumentTypeId = 7,
                            Email = "Gordon.Von@yahoo.com",
                            IdentificationNumber = "800717637",
                            LastName = "Bauch",
                            Name = "Carlotta",
                            OauthGoogle = "Carlie.Sanford76",
                            Password = "0Jp2zsn_zr",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 66,
                            DocumentTypeId = 7,
                            Email = "Sarai_Beier@yahoo.com",
                            IdentificationNumber = "797362976",
                            LastName = "Gaylord",
                            Name = "Rhoda",
                            OauthGoogle = "Mellie.Kuphal90",
                            Password = "5CO_P5SSR1",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 67,
                            DocumentTypeId = 7,
                            Email = "Arne.Block13@gmail.com",
                            IdentificationNumber = "792495285",
                            LastName = "Glover",
                            Name = "Thelma",
                            OauthGoogle = "Spencer11",
                            Password = "YqWfmm0ztT",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 68,
                            DocumentTypeId = 5,
                            Email = "Connor.Koelpin66@hotmail.com",
                            IdentificationNumber = "288962783",
                            LastName = "Robel",
                            Name = "Arnaldo",
                            Password = "oQr9uIktlh",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 69,
                            DocumentTypeId = 4,
                            Email = "Trystan75@hotmail.com",
                            IdentificationNumber = "351828141",
                            LastName = "Kuphal",
                            Name = "Stephanie",
                            Password = "Hf6rraiI2t",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 70,
                            DocumentTypeId = 5,
                            Email = "Clemmie_Padberg82@yahoo.com",
                            IdentificationNumber = "892326323",
                            LastName = "Mitchell",
                            Name = "Macy",
                            Password = "rRgkIoBw_Y",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 71,
                            DocumentTypeId = 6,
                            Email = "Lyda94@yahoo.com",
                            IdentificationNumber = "842615262",
                            LastName = "Kozey",
                            Name = "Reggie",
                            Password = "aXElFFG3Pe",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 72,
                            DocumentTypeId = 6,
                            Email = "Reid_Monahan97@gmail.com",
                            IdentificationNumber = "982267695",
                            LastName = "Wiza",
                            Name = "Myrtis",
                            OauthGoogle = "Zita29",
                            Password = "r2x0xRlUkN",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 73,
                            DocumentTypeId = 2,
                            Email = "Nico65@gmail.com",
                            IdentificationNumber = "200164459",
                            LastName = "Kautzer",
                            Name = "Scarlett",
                            Password = "RjhkU3yVYc",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 74,
                            DocumentTypeId = 6,
                            Email = "Mollie_Littel@hotmail.com",
                            IdentificationNumber = "783088538",
                            LastName = "Rohan",
                            Name = "Louvenia",
                            Password = "bYfmZBSfz3",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 75,
                            DocumentTypeId = 7,
                            Email = "Jeanette41@hotmail.com",
                            IdentificationNumber = "165571320",
                            LastName = "Wintheiser",
                            Name = "Justus",
                            Password = "mzaeUCV0zi",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 76,
                            DocumentTypeId = 5,
                            Email = "Madison72@hotmail.com",
                            IdentificationNumber = "349852702",
                            LastName = "Dietrich",
                            Name = "Heloise",
                            OauthGoogle = "Lia_Collins46",
                            Password = "o8FQ_jsn4l",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 77,
                            DocumentTypeId = 4,
                            Email = "Tavares_Pouros45@hotmail.com",
                            IdentificationNumber = "402482906",
                            LastName = "Homenick",
                            Name = "Gladyce",
                            Password = "F4FsIOUgkQ",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 78,
                            DocumentTypeId = 4,
                            Email = "Eunice_Nolan@hotmail.com",
                            IdentificationNumber = "073278130",
                            LastName = "Towne",
                            Name = "Mireya",
                            Password = "f1cgdDm1ev",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 79,
                            DocumentTypeId = 2,
                            Email = "Kennedi65@yahoo.com",
                            IdentificationNumber = "072800553",
                            LastName = "Hyatt",
                            Name = "Ozella",
                            OauthGoogle = "Malcolm71",
                            Password = "JjaYjLroEE",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 80,
                            DocumentTypeId = 5,
                            Email = "Addison.Douglas25@yahoo.com",
                            IdentificationNumber = "929446194",
                            LastName = "Robel",
                            Name = "Sigmund",
                            Password = "q8N5GEs0PN",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 81,
                            DocumentTypeId = 4,
                            Email = "Orlando_Glover@gmail.com",
                            IdentificationNumber = "999720719",
                            LastName = "Davis",
                            Name = "Hortense",
                            Password = "tW4v71G0PZ",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 82,
                            DocumentTypeId = 7,
                            Email = "Lloyd_McGlynn80@hotmail.com",
                            IdentificationNumber = "481705012",
                            LastName = "Ortiz",
                            Name = "Nora",
                            OauthGoogle = "Francesco82",
                            Password = "lblhuqlKSO",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 83,
                            DocumentTypeId = 6,
                            Email = "Samson24@yahoo.com",
                            IdentificationNumber = "662945369",
                            LastName = "Walker",
                            Name = "Kenna",
                            Password = "gjEK4AdC9B",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 84,
                            DocumentTypeId = 7,
                            Email = "Ramon79@hotmail.com",
                            IdentificationNumber = "194360691",
                            LastName = "Tromp",
                            Name = "Isabelle",
                            Password = "J3tES3aQpV",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 85,
                            DocumentTypeId = 6,
                            Email = "Eldora_Quigley@gmail.com",
                            IdentificationNumber = "199821692",
                            LastName = "Jones",
                            Name = "Rhiannon",
                            Password = "sClxboF2vT",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 86,
                            DocumentTypeId = 6,
                            Email = "Leda_Moen99@hotmail.com",
                            IdentificationNumber = "554233092",
                            LastName = "O'Kon",
                            Name = "Brannon",
                            Password = "S1rv2Vhoeu",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 87,
                            DocumentTypeId = 2,
                            Email = "Dorcas.Rodriguez@hotmail.com",
                            IdentificationNumber = "301884698",
                            LastName = "Jacobs",
                            Name = "Lawson",
                            OauthGoogle = "Sheridan_Armstrong",
                            Password = "g8fhECHbC_",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 88,
                            DocumentTypeId = 6,
                            Email = "Brendon_King@yahoo.com",
                            IdentificationNumber = "092009973",
                            LastName = "Russel",
                            Name = "Kevon",
                            OauthGoogle = "Gussie.Conn17",
                            Password = "dHPbaCKQlM",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 89,
                            DocumentTypeId = 5,
                            Email = "Keely_Klein19@yahoo.com",
                            IdentificationNumber = "690777871",
                            LastName = "Dicki",
                            Name = "Abraham",
                            Password = "E_xc6s83k4",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 90,
                            DocumentTypeId = 6,
                            Email = "Jeremy60@yahoo.com",
                            IdentificationNumber = "720536971",
                            LastName = "Wolff",
                            Name = "Syble",
                            Password = "4jTCtij_zK",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 91,
                            DocumentTypeId = 5,
                            Email = "Destin.Haag88@hotmail.com",
                            IdentificationNumber = "882244743",
                            LastName = "Mante",
                            Name = "Amir",
                            OauthGoogle = "Freeda_Bayer",
                            Password = "3LEFwTFU8W",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 92,
                            DocumentTypeId = 6,
                            Email = "Matilde.Lueilwitz27@yahoo.com",
                            IdentificationNumber = "162714698",
                            LastName = "Huels",
                            Name = "Jonas",
                            Password = "AahYWLNxFC",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 93,
                            DocumentTypeId = 3,
                            Email = "Nicolette61@yahoo.com",
                            IdentificationNumber = "978326755",
                            LastName = "Schamberger",
                            Name = "Savanna",
                            OauthGoogle = "Esteban97",
                            Password = "UON8b1LIN0",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 94,
                            DocumentTypeId = 4,
                            Email = "Dangelo.Christiansen@gmail.com",
                            IdentificationNumber = "044379370",
                            LastName = "Baumbach",
                            Name = "Marcelle",
                            OauthGoogle = "Allene.Schimmel",
                            Password = "LENPSJT4k4",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 95,
                            DocumentTypeId = 1,
                            Email = "Elwyn17@hotmail.com",
                            IdentificationNumber = "722864633",
                            LastName = "Kreiger",
                            Name = "Janis",
                            Password = "j40XgZ7RcR",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 96,
                            DocumentTypeId = 3,
                            Email = "Oceane.Paucek@yahoo.com",
                            IdentificationNumber = "718602350",
                            LastName = "Vandervort",
                            Name = "Opal",
                            OauthGoogle = "Teresa.Cruickshank1",
                            Password = "pNfJtA0goo",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 97,
                            DocumentTypeId = 7,
                            Email = "Eldon12@gmail.com",
                            IdentificationNumber = "653034579",
                            LastName = "Brekke",
                            Name = "Jane",
                            OauthGoogle = "Marian_Jacobs46",
                            Password = "gUtSHJMkH3",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 98,
                            DocumentTypeId = 5,
                            Email = "Mateo10@hotmail.com",
                            IdentificationNumber = "702214277",
                            LastName = "Price",
                            Name = "Lolita",
                            OauthGoogle = "Jerome.Cummings64",
                            Password = "EiDJVJROO0",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 99,
                            DocumentTypeId = 6,
                            Email = "Oceane_Blanda@hotmail.com",
                            IdentificationNumber = "037499605",
                            LastName = "Wiegand",
                            Name = "Fabian",
                            OauthGoogle = "Yvonne_Koelpin66",
                            Password = "s9mWyNLI7r",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 100,
                            DocumentTypeId = 3,
                            Email = "Yvette71@yahoo.com",
                            IdentificationNumber = "092956977",
                            LastName = "Pacocha",
                            Name = "Isaias",
                            OauthGoogle = "Katlynn18",
                            Password = "iqKyrpSHEm",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.Rol", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
