// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurePoll_BE.Data;

#nullable disable

namespace SecurePoll_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908172617_AddColumnHasIntoVoters")]
    partial class AddColumnHasIntoVoters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SecurePoll_BE.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int")
                        .HasColumnName("election_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("candidates");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("document_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CC",
                            Name = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "TI",
                            Name = "Tarjeta de Identidad"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PS",
                            Name = "Pasaporte"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "NIT",
                            Name = "Número de Identificación Tributaria"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CE",
                            Name = "Cédula de Extranjería"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "RC",
                            Name = "Registro Civil"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "PEP",
                            Name = "Permiso Especial de Permanencia"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("elections");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Votante"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Candidato"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OauthGoogle")
                        .HasColumnType("longtext")
                        .HasColumnName("oauth_google");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext")
                        .HasColumnName("public_key");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentTypeId = 6,
                            Email = "Tamia.Reynolds52@gmail.com",
                            IdentificationNumber = "573978560",
                            LastName = "Kuhic",
                            Name = "Noemi",
                            OauthGoogle = "Elena62",
                            Password = "FMWAe_bNCV",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 2,
                            DocumentTypeId = 7,
                            Email = "Cleve.Nolan14@hotmail.com",
                            IdentificationNumber = "569984993",
                            LastName = "Gusikowski",
                            Name = "Janessa",
                            Password = "0xAUTpY2cY",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            DocumentTypeId = 3,
                            Email = "Antonio.Crona86@yahoo.com",
                            IdentificationNumber = "068470970",
                            LastName = "Kozey",
                            Name = "Delphine",
                            OauthGoogle = "Mae5",
                            Password = "53PQKe3N7H",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 4,
                            DocumentTypeId = 6,
                            Email = "Keaton_DuBuque21@gmail.com",
                            IdentificationNumber = "240194781",
                            LastName = "Rutherford",
                            Name = "Aniya",
                            Password = "2C8lSb7z2W",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            DocumentTypeId = 3,
                            Email = "Asia_Dickinson61@gmail.com",
                            IdentificationNumber = "260887329",
                            LastName = "Padberg",
                            Name = "Tiana",
                            Password = "XfhzOD6kKg",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            DocumentTypeId = 4,
                            Email = "Arvel90@hotmail.com",
                            IdentificationNumber = "309709487",
                            LastName = "Stracke",
                            Name = "Mafalda",
                            OauthGoogle = "Anthony_Glover",
                            Password = "UYFtGExQrZ",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 7,
                            DocumentTypeId = 6,
                            Email = "Vernon64@yahoo.com",
                            IdentificationNumber = "260859794",
                            LastName = "Feest",
                            Name = "Wellington",
                            OauthGoogle = "Kiley.Windler23",
                            Password = "hcuL5A3Zwi",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 8,
                            DocumentTypeId = 2,
                            Email = "Eli_Heller@yahoo.com",
                            IdentificationNumber = "376448863",
                            LastName = "Stokes",
                            Name = "Hillard",
                            OauthGoogle = "Rebeka15",
                            Password = "ukMGyOpCYe",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 9,
                            DocumentTypeId = 4,
                            Email = "Nettie.Johnston@yahoo.com",
                            IdentificationNumber = "095635680",
                            LastName = "DuBuque",
                            Name = "Lera",
                            Password = "u6a8TAm15d",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            DocumentTypeId = 6,
                            Email = "Mariah_Heidenreich67@yahoo.com",
                            IdentificationNumber = "272331381",
                            LastName = "Dicki",
                            Name = "Noelia",
                            OauthGoogle = "Lee12",
                            Password = "0mk0_Is8yp",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            DocumentTypeId = 7,
                            Email = "Tina.Ferry@hotmail.com",
                            IdentificationNumber = "423072201",
                            LastName = "Anderson",
                            Name = "Jammie",
                            Password = "cq71lRmOUA",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 12,
                            DocumentTypeId = 1,
                            Email = "Melyssa42@gmail.com",
                            IdentificationNumber = "191448580",
                            LastName = "Green",
                            Name = "Lilian",
                            OauthGoogle = "Shanon76",
                            Password = "t9iA610xVT",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            DocumentTypeId = 7,
                            Email = "Stacey34@hotmail.com",
                            IdentificationNumber = "860371617",
                            LastName = "Bergstrom",
                            Name = "Dewitt",
                            OauthGoogle = "Andrew86",
                            Password = "LyDO2lZnFX",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 14,
                            DocumentTypeId = 6,
                            Email = "Audie_Jones45@hotmail.com",
                            IdentificationNumber = "950843152",
                            LastName = "Windler",
                            Name = "Daisha",
                            OauthGoogle = "Lon.Morar80",
                            Password = "2G733K1hfm",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 15,
                            DocumentTypeId = 2,
                            Email = "Vidal_Kris23@yahoo.com",
                            IdentificationNumber = "328104702",
                            LastName = "Kuhlman",
                            Name = "Lavada",
                            OauthGoogle = "Serenity_Runolfsson47",
                            Password = "sErtuLJzSB",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            DocumentTypeId = 6,
                            Email = "Jennings.Herman@yahoo.com",
                            IdentificationNumber = "526448034",
                            LastName = "McGlynn",
                            Name = "Ryder",
                            OauthGoogle = "Arianna.Walker",
                            Password = "GCD_7XThtz",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 17,
                            DocumentTypeId = 7,
                            Email = "Chaya_Lowe@hotmail.com",
                            IdentificationNumber = "903536559",
                            LastName = "Mohr",
                            Name = "Dillan",
                            OauthGoogle = "Elaina.Conn",
                            Password = "egDr2PLtVB",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            DocumentTypeId = 1,
                            Email = "Paris48@gmail.com",
                            IdentificationNumber = "544888125",
                            LastName = "Bergnaum",
                            Name = "Holly",
                            OauthGoogle = "Kiley11",
                            Password = "rQZfxE99nI",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 19,
                            DocumentTypeId = 4,
                            Email = "Berry_Wilkinson@hotmail.com",
                            IdentificationNumber = "581908205",
                            LastName = "Becker",
                            Name = "Bobby",
                            OauthGoogle = "Lisette67",
                            Password = "UvBJLLd0s8",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            DocumentTypeId = 2,
                            Email = "Loren_Koch@hotmail.com",
                            IdentificationNumber = "261710618",
                            LastName = "Torphy",
                            Name = "Johnpaul",
                            Password = "vXdd_Myrfu",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 21,
                            DocumentTypeId = 4,
                            Email = "Sarina94@gmail.com",
                            IdentificationNumber = "748771800",
                            LastName = "Hauck",
                            Name = "Easter",
                            Password = "2CWAaDEIMz",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 22,
                            DocumentTypeId = 4,
                            Email = "Enos_Cremin51@gmail.com",
                            IdentificationNumber = "551287453",
                            LastName = "O'Conner",
                            Name = "Gabe",
                            Password = "yYsYqjxx6D",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 23,
                            DocumentTypeId = 4,
                            Email = "Laverna_Fisher23@yahoo.com",
                            IdentificationNumber = "087514597",
                            LastName = "Waelchi",
                            Name = "Jennifer",
                            Password = "k1BGg1DvSW",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 24,
                            DocumentTypeId = 7,
                            Email = "Tavares.Schaden26@gmail.com",
                            IdentificationNumber = "169169233",
                            LastName = "Macejkovic",
                            Name = "Stephany",
                            OauthGoogle = "Ford38",
                            Password = "7Q6xNEsJtp",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 25,
                            DocumentTypeId = 5,
                            Email = "Madison.Davis@hotmail.com",
                            IdentificationNumber = "367966036",
                            LastName = "Hartmann",
                            Name = "Adele",
                            OauthGoogle = "Eduardo99",
                            Password = "9wEIRPkbeL",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 26,
                            DocumentTypeId = 2,
                            Email = "Chelsie_Roberts@gmail.com",
                            IdentificationNumber = "281777422",
                            LastName = "Bailey",
                            Name = "Destin",
                            Password = "8fYSOe4hnF",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            DocumentTypeId = 2,
                            Email = "Elwin_Hoppe21@hotmail.com",
                            IdentificationNumber = "126258780",
                            LastName = "Borer",
                            Name = "Kareem",
                            Password = "2fFy6YCZ6D",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 28,
                            DocumentTypeId = 1,
                            Email = "Tony.Turner@yahoo.com",
                            IdentificationNumber = "267702638",
                            LastName = "Spencer",
                            Name = "Billie",
                            OauthGoogle = "Chance.Streich79",
                            Password = "Re5S61omAG",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 29,
                            DocumentTypeId = 1,
                            Email = "Jessie33@yahoo.com",
                            IdentificationNumber = "815270530",
                            LastName = "Satterfield",
                            Name = "Geovanny",
                            Password = "ifcAKtM03N",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 30,
                            DocumentTypeId = 5,
                            Email = "Jamie5@hotmail.com",
                            IdentificationNumber = "422999581",
                            LastName = "Reynolds",
                            Name = "Anahi",
                            Password = "75c1n7N52B",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 31,
                            DocumentTypeId = 5,
                            Email = "Effie_Bednar@yahoo.com",
                            IdentificationNumber = "930742965",
                            LastName = "Sauer",
                            Name = "Abigail",
                            OauthGoogle = "Norbert.Hilll8",
                            Password = "gDfPRFEOTi",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 32,
                            DocumentTypeId = 4,
                            Email = "Olen77@hotmail.com",
                            IdentificationNumber = "591147882",
                            LastName = "Jaskolski",
                            Name = "Bert",
                            Password = "Yqm3OkstZC",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 33,
                            DocumentTypeId = 5,
                            Email = "Eda.Klein@hotmail.com",
                            IdentificationNumber = "280502184",
                            LastName = "Ferry",
                            Name = "Jerald",
                            OauthGoogle = "Eloise.Jakubowski79",
                            Password = "Mul7TPRgtg",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 34,
                            DocumentTypeId = 1,
                            Email = "Ryan65@hotmail.com",
                            IdentificationNumber = "427813590",
                            LastName = "Mohr",
                            Name = "America",
                            Password = "1yAlqjGm0G",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 35,
                            DocumentTypeId = 7,
                            Email = "Justen48@gmail.com",
                            IdentificationNumber = "307518041",
                            LastName = "Dach",
                            Name = "Dalton",
                            OauthGoogle = "Ned_Romaguera",
                            Password = "erQpyR8GXj",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 36,
                            DocumentTypeId = 4,
                            Email = "Cristopher_Paucek@gmail.com",
                            IdentificationNumber = "590968773",
                            LastName = "Weissnat",
                            Name = "Donnell",
                            OauthGoogle = "Mara_Hilll",
                            Password = "FixyQoZSon",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 37,
                            DocumentTypeId = 6,
                            Email = "Turner.Bergstrom27@hotmail.com",
                            IdentificationNumber = "224319603",
                            LastName = "Farrell",
                            Name = "Nicola",
                            OauthGoogle = "Rasheed29",
                            Password = "BGLyHGCp70",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 38,
                            DocumentTypeId = 4,
                            Email = "Archibald_Mayer@hotmail.com",
                            IdentificationNumber = "571792872",
                            LastName = "Huels",
                            Name = "Brooks",
                            OauthGoogle = "Roger_Kiehn89",
                            Password = "tHKLb8v11V",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 39,
                            DocumentTypeId = 7,
                            Email = "Elaina23@yahoo.com",
                            IdentificationNumber = "360012285",
                            LastName = "Kihn",
                            Name = "Leonard",
                            OauthGoogle = "Linnea64",
                            Password = "IoW4FmoPwx",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 40,
                            DocumentTypeId = 6,
                            Email = "Rachelle.Dibbert@gmail.com",
                            IdentificationNumber = "878657846",
                            LastName = "Schaefer",
                            Name = "Reese",
                            Password = "Oze6YMY0ZC",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 41,
                            DocumentTypeId = 1,
                            Email = "Bianka79@yahoo.com",
                            IdentificationNumber = "250692108",
                            LastName = "Reilly",
                            Name = "Milo",
                            Password = "SJCBnL731Z",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 42,
                            DocumentTypeId = 3,
                            Email = "Diana29@gmail.com",
                            IdentificationNumber = "757047928",
                            LastName = "Emmerich",
                            Name = "Eula",
                            Password = "7OsHMVTO1j",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 43,
                            DocumentTypeId = 5,
                            Email = "Johathan.Littel@yahoo.com",
                            IdentificationNumber = "700942134",
                            LastName = "Schuppe",
                            Name = "Koby",
                            OauthGoogle = "Edmund_Steuber",
                            Password = "JCYa2lIOLx",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 44,
                            DocumentTypeId = 5,
                            Email = "Gillian50@yahoo.com",
                            IdentificationNumber = "548736212",
                            LastName = "Quitzon",
                            Name = "Euna",
                            OauthGoogle = "Junius.Waters",
                            Password = "51scUcqgxv",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            DocumentTypeId = 3,
                            Email = "Lori88@yahoo.com",
                            IdentificationNumber = "606675903",
                            LastName = "Cummerata",
                            Name = "Hilma",
                            OauthGoogle = "Robb.Aufderhar96",
                            Password = "DdL91qV8FR",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            DocumentTypeId = 7,
                            Email = "Elwin65@gmail.com",
                            IdentificationNumber = "130216278",
                            LastName = "Lueilwitz",
                            Name = "Krista",
                            Password = "5B9dpbcvyf",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 47,
                            DocumentTypeId = 3,
                            Email = "Rogelio32@gmail.com",
                            IdentificationNumber = "934930298",
                            LastName = "Rutherford",
                            Name = "Lisa",
                            Password = "x0vrmGDnKa",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 48,
                            DocumentTypeId = 3,
                            Email = "Ignatius11@gmail.com",
                            IdentificationNumber = "655220931",
                            LastName = "Kshlerin",
                            Name = "Bell",
                            Password = "GUTFwA6YDN",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 49,
                            DocumentTypeId = 5,
                            Email = "Karen_Nikolaus@gmail.com",
                            IdentificationNumber = "098597212",
                            LastName = "Cronin",
                            Name = "Cory",
                            OauthGoogle = "Adela.Cremin1",
                            Password = "JXihO0YUrI",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 50,
                            DocumentTypeId = 5,
                            Email = "Mark_Simonis@yahoo.com",
                            IdentificationNumber = "791440705",
                            LastName = "Schimmel",
                            Name = "Clifton",
                            OauthGoogle = "Allison89",
                            Password = "ubrkWNB7MR",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            DocumentTypeId = 1,
                            Email = "Adrain.Hane36@gmail.com",
                            IdentificationNumber = "596505562",
                            LastName = "Stoltenberg",
                            Name = "Dolores",
                            Password = "UvlINScCoi",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 52,
                            DocumentTypeId = 7,
                            Email = "Cory66@gmail.com",
                            IdentificationNumber = "975229760",
                            LastName = "Block",
                            Name = "Roselyn",
                            Password = "9PKxwe0ixE",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 53,
                            DocumentTypeId = 3,
                            Email = "Sidney.Emard@hotmail.com",
                            IdentificationNumber = "584195584",
                            LastName = "Rath",
                            Name = "Maegan",
                            Password = "sHAfRapyLx",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 54,
                            DocumentTypeId = 1,
                            Email = "Antonia52@hotmail.com",
                            IdentificationNumber = "709953541",
                            LastName = "Reynolds",
                            Name = "Kathryne",
                            OauthGoogle = "Renee65",
                            Password = "DcVgZvege8",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 55,
                            DocumentTypeId = 2,
                            Email = "Dominique68@hotmail.com",
                            IdentificationNumber = "356245452",
                            LastName = "Kutch",
                            Name = "Florida",
                            OauthGoogle = "Shakira.Crona9",
                            Password = "H5R8bmHX1K",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 56,
                            DocumentTypeId = 5,
                            Email = "Miguel15@hotmail.com",
                            IdentificationNumber = "526375133",
                            LastName = "Bauch",
                            Name = "Thad",
                            OauthGoogle = "Alanis19",
                            Password = "U46ytpqolj",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 57,
                            DocumentTypeId = 6,
                            Email = "Alan.Pollich36@hotmail.com",
                            IdentificationNumber = "909196702",
                            LastName = "Stehr",
                            Name = "Kyleigh",
                            OauthGoogle = "Gisselle.Bergnaum70",
                            Password = "ny7CP2_M7y",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 58,
                            DocumentTypeId = 6,
                            Email = "Deon_Olson8@gmail.com",
                            IdentificationNumber = "877128718",
                            LastName = "Grady",
                            Name = "Claudia",
                            Password = "zLCGrr_Jg6",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 59,
                            DocumentTypeId = 3,
                            Email = "Reagan_Brown@gmail.com",
                            IdentificationNumber = "891685004",
                            LastName = "Lynch",
                            Name = "Judge",
                            OauthGoogle = "Ansley.Hettinger88",
                            Password = "KEkk9DHE2R",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 60,
                            DocumentTypeId = 6,
                            Email = "Tyreek55@hotmail.com",
                            IdentificationNumber = "320152456",
                            LastName = "Reichert",
                            Name = "Kellen",
                            Password = "a9d1XO5R7f",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 61,
                            DocumentTypeId = 6,
                            Email = "Issac.Auer81@gmail.com",
                            IdentificationNumber = "369408883",
                            LastName = "Abshire",
                            Name = "Kara",
                            OauthGoogle = "Cheyanne.Frami24",
                            Password = "blnIuf1TMW",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 62,
                            DocumentTypeId = 7,
                            Email = "Kevon_Herzog33@gmail.com",
                            IdentificationNumber = "929872652",
                            LastName = "Hettinger",
                            Name = "Scottie",
                            OauthGoogle = "Nicholas53",
                            Password = "waoLMXxamF",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 63,
                            DocumentTypeId = 2,
                            Email = "Estel_Ritchie85@hotmail.com",
                            IdentificationNumber = "688419582",
                            LastName = "Roberts",
                            Name = "Molly",
                            Password = "3HTBNRyWpD",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 64,
                            DocumentTypeId = 2,
                            Email = "Claude.Weimann@hotmail.com",
                            IdentificationNumber = "789065398",
                            LastName = "Turcotte",
                            Name = "Justina",
                            Password = "VKUo31IXQ6",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 65,
                            DocumentTypeId = 1,
                            Email = "Tressa_Schaefer3@hotmail.com",
                            IdentificationNumber = "714854034",
                            LastName = "Kassulke",
                            Name = "Sister",
                            OauthGoogle = "Emelia76",
                            Password = "50nx7d8U5k",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 66,
                            DocumentTypeId = 6,
                            Email = "Katelyn.Orn@yahoo.com",
                            IdentificationNumber = "707641487",
                            LastName = "Mayert",
                            Name = "Jennie",
                            Password = "Fb59Ghu2f4",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 67,
                            DocumentTypeId = 1,
                            Email = "Korbin39@yahoo.com",
                            IdentificationNumber = "928362412",
                            LastName = "Stamm",
                            Name = "Ardella",
                            Password = "xYnIucj21f",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 68,
                            DocumentTypeId = 2,
                            Email = "Natasha.Toy67@hotmail.com",
                            IdentificationNumber = "316382895",
                            LastName = "Weissnat",
                            Name = "Courtney",
                            Password = "SKMqFl2xNW",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 69,
                            DocumentTypeId = 6,
                            Email = "Eleazar58@hotmail.com",
                            IdentificationNumber = "704078276",
                            LastName = "Collins",
                            Name = "Brown",
                            Password = "Y8NGceT_jp",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 70,
                            DocumentTypeId = 5,
                            Email = "Lera_Nicolas@gmail.com",
                            IdentificationNumber = "794898582",
                            LastName = "Hodkiewicz",
                            Name = "Carley",
                            OauthGoogle = "Maximo88",
                            Password = "8STHbq6J9g",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 71,
                            DocumentTypeId = 4,
                            Email = "Waino_Dickinson86@gmail.com",
                            IdentificationNumber = "378779247",
                            LastName = "Armstrong",
                            Name = "Edna",
                            OauthGoogle = "Ines0",
                            Password = "YKzTjPuaxV",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 72,
                            DocumentTypeId = 3,
                            Email = "Hollis29@hotmail.com",
                            IdentificationNumber = "011943354",
                            LastName = "Larson",
                            Name = "Santos",
                            Password = "KVanPnv2sc",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 73,
                            DocumentTypeId = 1,
                            Email = "Sanford_Kassulke8@gmail.com",
                            IdentificationNumber = "584691614",
                            LastName = "Shields",
                            Name = "Mollie",
                            OauthGoogle = "Corrine_Witting82",
                            Password = "yX3yw0vRna",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 74,
                            DocumentTypeId = 6,
                            Email = "Cristian.Connelly@hotmail.com",
                            IdentificationNumber = "143577218",
                            LastName = "Miller",
                            Name = "Korbin",
                            Password = "xr57ADMbvg",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 75,
                            DocumentTypeId = 4,
                            Email = "Bill_Robel93@yahoo.com",
                            IdentificationNumber = "536404216",
                            LastName = "Tillman",
                            Name = "Dale",
                            Password = "oEtu6AcAI0",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 76,
                            DocumentTypeId = 5,
                            Email = "Kris32@gmail.com",
                            IdentificationNumber = "987904777",
                            LastName = "Abbott",
                            Name = "Alia",
                            OauthGoogle = "Ena_Emmerich9",
                            Password = "ZWlJhg869k",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 77,
                            DocumentTypeId = 3,
                            Email = "Marisol.Padberg@yahoo.com",
                            IdentificationNumber = "490012246",
                            LastName = "Torphy",
                            Name = "Darrick",
                            Password = "Au0E4fpfwc",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 78,
                            DocumentTypeId = 5,
                            Email = "Tyshawn.Kunde2@gmail.com",
                            IdentificationNumber = "675171213",
                            LastName = "Krajcik",
                            Name = "Christ",
                            Password = "4TfBeg8QaJ",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 79,
                            DocumentTypeId = 4,
                            Email = "Maximo_Brekke@yahoo.com",
                            IdentificationNumber = "309885406",
                            LastName = "Zieme",
                            Name = "Georgiana",
                            Password = "dxh8N4Mwo_",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 80,
                            DocumentTypeId = 1,
                            Email = "Jayda.Hyatt@hotmail.com",
                            IdentificationNumber = "883297456",
                            LastName = "Bergnaum",
                            Name = "Cecilia",
                            Password = "4LWLVG2f8U",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 81,
                            DocumentTypeId = 4,
                            Email = "Julie.Walker9@hotmail.com",
                            IdentificationNumber = "306205609",
                            LastName = "Huels",
                            Name = "Myrtis",
                            Password = "8pAcKxz0gh",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 82,
                            DocumentTypeId = 3,
                            Email = "Zella_Waelchi32@yahoo.com",
                            IdentificationNumber = "839315249",
                            LastName = "Kuhlman",
                            Name = "Damian",
                            Password = "oYYMY6hspk",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 83,
                            DocumentTypeId = 6,
                            Email = "Gay.Towne@gmail.com",
                            IdentificationNumber = "603960409",
                            LastName = "Larkin",
                            Name = "Retha",
                            Password = "bYjrAhz88L",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 84,
                            DocumentTypeId = 6,
                            Email = "Alexzander.Nienow12@gmail.com",
                            IdentificationNumber = "019196198",
                            LastName = "Reinger",
                            Name = "Camilla",
                            OauthGoogle = "Carmela.Hamill97",
                            Password = "t8pwcSQ36Y",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 85,
                            DocumentTypeId = 4,
                            Email = "Deangelo_Corwin@yahoo.com",
                            IdentificationNumber = "673524935",
                            LastName = "Walsh",
                            Name = "Magnolia",
                            OauthGoogle = "Delia18",
                            Password = "iVYX1Z5sek",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 86,
                            DocumentTypeId = 7,
                            Email = "Roger_Koelpin82@gmail.com",
                            IdentificationNumber = "296062090",
                            LastName = "Monahan",
                            Name = "Noelia",
                            Password = "EJqoaUVJRF",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 87,
                            DocumentTypeId = 2,
                            Email = "Oren.Homenick@gmail.com",
                            IdentificationNumber = "189054016",
                            LastName = "Krajcik",
                            Name = "Una",
                            Password = "n753uH2M4i",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 88,
                            DocumentTypeId = 2,
                            Email = "Jodie60@yahoo.com",
                            IdentificationNumber = "463301192",
                            LastName = "Gutkowski",
                            Name = "Kareem",
                            Password = "XcPBkMO3yV",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 89,
                            DocumentTypeId = 6,
                            Email = "Dereck.Erdman@gmail.com",
                            IdentificationNumber = "365978703",
                            LastName = "Gusikowski",
                            Name = "Angelita",
                            Password = "hQlqY7Lszj",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 90,
                            DocumentTypeId = 1,
                            Email = "Will0@gmail.com",
                            IdentificationNumber = "238346753",
                            LastName = "Lynch",
                            Name = "Loren",
                            Password = "yjkhdxFhAP",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 91,
                            DocumentTypeId = 1,
                            Email = "Karolann.Gleason52@yahoo.com",
                            IdentificationNumber = "117675546",
                            LastName = "Waelchi",
                            Name = "Amara",
                            Password = "7Pemrt5cjH",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 92,
                            DocumentTypeId = 7,
                            Email = "Lorna.Klein97@gmail.com",
                            IdentificationNumber = "615760571",
                            LastName = "Krajcik",
                            Name = "Elody",
                            Password = "hCvg3tqIw8",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 93,
                            DocumentTypeId = 1,
                            Email = "Emerald.Herzog75@hotmail.com",
                            IdentificationNumber = "916373326",
                            LastName = "Waters",
                            Name = "Nina",
                            OauthGoogle = "Xzavier.Nienow34",
                            Password = "Mei1H1R7BE",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 94,
                            DocumentTypeId = 6,
                            Email = "Troy36@yahoo.com",
                            IdentificationNumber = "972825860",
                            LastName = "Heidenreich",
                            Name = "Randal",
                            OauthGoogle = "Aidan_Dietrich",
                            Password = "MKQynupzzH",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 95,
                            DocumentTypeId = 4,
                            Email = "Gunnar_Hansen@gmail.com",
                            IdentificationNumber = "894580878",
                            LastName = "Rogahn",
                            Name = "Melany",
                            OauthGoogle = "Felicia_Effertz",
                            Password = "VHE3WVDUPT",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 96,
                            DocumentTypeId = 2,
                            Email = "Wyman39@gmail.com",
                            IdentificationNumber = "459654943",
                            LastName = "Gibson",
                            Name = "Garnet",
                            OauthGoogle = "Aaliyah_Hagenes",
                            Password = "WuOelojGP2",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 97,
                            DocumentTypeId = 7,
                            Email = "Zena_Cummerata@yahoo.com",
                            IdentificationNumber = "819196866",
                            LastName = "Hessel",
                            Name = "Rosie",
                            OauthGoogle = "Melissa.Walker",
                            Password = "PdBsun3wy2",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 98,
                            DocumentTypeId = 4,
                            Email = "Estelle_Kirlin@yahoo.com",
                            IdentificationNumber = "881011070",
                            LastName = "Mayer",
                            Name = "Joe",
                            Password = "J8XhJj49w7",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 99,
                            DocumentTypeId = 6,
                            Email = "Matilde77@hotmail.com",
                            IdentificationNumber = "258579165",
                            LastName = "Mann",
                            Name = "Finn",
                            Password = "TyHkgf5WXv",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 100,
                            DocumentTypeId = 6,
                            Email = "Arnoldo72@yahoo.com",
                            IdentificationNumber = "122994830",
                            LastName = "Bauch",
                            Name = "Jolie",
                            Password = "btkhzHNZR6",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int")
                        .HasColumnName("election_id");

                    b.Property<int>("HashVote")
                        .HasColumnType("int")
                        .HasColumnName("hash_vote");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("voters");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Candidate", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.Rol", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Voter", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
