// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurePoll_BE.Data;

#nullable disable

namespace SecurePoll_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908034111_AddTableVoters")]
    partial class AddTableVoters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SecurePoll_BE.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("document_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CC",
                            Name = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "TI",
                            Name = "Tarjeta de Identidad"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PS",
                            Name = "Pasaporte"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "NIT",
                            Name = "Número de Identificación Tributaria"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CE",
                            Name = "Cédula de Extranjería"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "RC",
                            Name = "Registro Civil"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "PEP",
                            Name = "Permiso Especial de Permanencia"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("elections");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Votante"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Candidato"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OauthGoogle")
                        .HasColumnType("longtext")
                        .HasColumnName("oauth_google");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentTypeId = 6,
                            Email = "Micheal1@yahoo.com",
                            IdentificationNumber = "599822134",
                            LastName = "Grimes",
                            Name = "Fay",
                            OauthGoogle = "Concepcion.Barton11",
                            Password = "NbL0cTnlKc",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            DocumentTypeId = 3,
                            Email = "Karlie.Casper92@yahoo.com",
                            IdentificationNumber = "809221627",
                            LastName = "Thompson",
                            Name = "Gillian",
                            OauthGoogle = "Jaime_OReilly",
                            Password = "Td5Vl5St0V",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 3,
                            DocumentTypeId = 3,
                            Email = "Donnie81@hotmail.com",
                            IdentificationNumber = "032362458",
                            LastName = "Bins",
                            Name = "Seth",
                            OauthGoogle = "Beulah84",
                            Password = "Vr0YgeDPXQ",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 4,
                            DocumentTypeId = 3,
                            Email = "Molly.Carter@hotmail.com",
                            IdentificationNumber = "622406537",
                            LastName = "Rodriguez",
                            Name = "Armand",
                            Password = "1mEYQ2sCt6",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 5,
                            DocumentTypeId = 4,
                            Email = "Jillian87@hotmail.com",
                            IdentificationNumber = "918265483",
                            LastName = "Cartwright",
                            Name = "Madelynn",
                            OauthGoogle = "Collin.King49",
                            Password = "VkYuhSSRzL",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 6,
                            DocumentTypeId = 2,
                            Email = "Krystina32@gmail.com",
                            IdentificationNumber = "580471999",
                            LastName = "Stark",
                            Name = "Daphnee",
                            OauthGoogle = "Kacey57",
                            Password = "0qIj2RsZ1I",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 7,
                            DocumentTypeId = 5,
                            Email = "Devonte24@yahoo.com",
                            IdentificationNumber = "252704470",
                            LastName = "Bednar",
                            Name = "Constance",
                            OauthGoogle = "Gregg.Hyatt",
                            Password = "gExXRSbvlG",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 8,
                            DocumentTypeId = 5,
                            Email = "Santino_Maggio@gmail.com",
                            IdentificationNumber = "878908918",
                            LastName = "Olson",
                            Name = "Kellie",
                            OauthGoogle = "Jessica26",
                            Password = "zX7RIoM2Wj",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 9,
                            DocumentTypeId = 2,
                            Email = "Lorena95@gmail.com",
                            IdentificationNumber = "235115971",
                            LastName = "Beer",
                            Name = "Marcel",
                            OauthGoogle = "Hallie.Murphy",
                            Password = "y6as2B8qS5",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 10,
                            DocumentTypeId = 7,
                            Email = "Frederick18@yahoo.com",
                            IdentificationNumber = "922285114",
                            LastName = "Luettgen",
                            Name = "Willie",
                            Password = "o7sQZ9AhJX",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 11,
                            DocumentTypeId = 1,
                            Email = "Domenick.Smitham34@gmail.com",
                            IdentificationNumber = "385267121",
                            LastName = "Beahan",
                            Name = "Lillian",
                            OauthGoogle = "Carroll.Robel99",
                            Password = "bWomGCo5TK",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 12,
                            DocumentTypeId = 2,
                            Email = "Tara.Waters88@yahoo.com",
                            IdentificationNumber = "646988258",
                            LastName = "Walter",
                            Name = "Anastacio",
                            OauthGoogle = "Alexys10",
                            Password = "6vL5FFph50",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 13,
                            DocumentTypeId = 5,
                            Email = "Keyon.OConnell21@gmail.com",
                            IdentificationNumber = "668935253",
                            LastName = "Schoen",
                            Name = "Timothy",
                            OauthGoogle = "Cora_Cronin",
                            Password = "BqtIuIVbfl",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 14,
                            DocumentTypeId = 5,
                            Email = "Bonnie_Cummings56@yahoo.com",
                            IdentificationNumber = "244142997",
                            LastName = "Cartwright",
                            Name = "Solon",
                            Password = "fweP4pYcHm",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 15,
                            DocumentTypeId = 3,
                            Email = "Lilyan_Kling61@yahoo.com",
                            IdentificationNumber = "761122531",
                            LastName = "Ortiz",
                            Name = "Maxine",
                            Password = "y9uVSLe_AP",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 16,
                            DocumentTypeId = 7,
                            Email = "Genesis_Raynor43@hotmail.com",
                            IdentificationNumber = "000327573",
                            LastName = "Koch",
                            Name = "Mackenzie",
                            OauthGoogle = "Arvel_Dooley95",
                            Password = "sjn3hlXl2m",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 17,
                            DocumentTypeId = 5,
                            Email = "Colton.Pouros@gmail.com",
                            IdentificationNumber = "196953953",
                            LastName = "Simonis",
                            Name = "Hardy",
                            OauthGoogle = "Katrine_Armstrong2",
                            Password = "jXHidQhly2",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 18,
                            DocumentTypeId = 4,
                            Email = "Shanny70@gmail.com",
                            IdentificationNumber = "337048796",
                            LastName = "Bruen",
                            Name = "Marilie",
                            Password = "5sTNIR6FZf",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            DocumentTypeId = 1,
                            Email = "Aimee.Kulas@yahoo.com",
                            IdentificationNumber = "772324909",
                            LastName = "Schiller",
                            Name = "Veda",
                            OauthGoogle = "Dexter.Bechtelar87",
                            Password = "anmhRYGgvL",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 20,
                            DocumentTypeId = 7,
                            Email = "Cornelius12@hotmail.com",
                            IdentificationNumber = "698433787",
                            LastName = "Grant",
                            Name = "Kane",
                            Password = "faZXdLjuk2",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 21,
                            DocumentTypeId = 4,
                            Email = "Gussie.Gibson@hotmail.com",
                            IdentificationNumber = "456123174",
                            LastName = "Reichert",
                            Name = "Vida",
                            OauthGoogle = "Zander.Miller",
                            Password = "N9IuLYhCzy",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            DocumentTypeId = 2,
                            Email = "Henderson.Yundt@gmail.com",
                            IdentificationNumber = "972710364",
                            LastName = "Walker",
                            Name = "Phoebe",
                            Password = "CcExwLnGSX",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 23,
                            DocumentTypeId = 3,
                            Email = "Cecilia_Schmidt@yahoo.com",
                            IdentificationNumber = "283864119",
                            LastName = "Farrell",
                            Name = "Lilly",
                            Password = "GiATaOuICR",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 24,
                            DocumentTypeId = 3,
                            Email = "Mohammed.Bednar@yahoo.com",
                            IdentificationNumber = "734458570",
                            LastName = "Kiehn",
                            Name = "Damian",
                            Password = "PKiQrbyREY",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 25,
                            DocumentTypeId = 5,
                            Email = "Allen_Ebert@hotmail.com",
                            IdentificationNumber = "916401757",
                            LastName = "Mayer",
                            Name = "Imani",
                            OauthGoogle = "Raul.Weber",
                            Password = "sQZfEUiio2",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 26,
                            DocumentTypeId = 4,
                            Email = "Abelardo_Nitzsche@yahoo.com",
                            IdentificationNumber = "649383216",
                            LastName = "Moore",
                            Name = "Marge",
                            OauthGoogle = "Jamil_Kautzer",
                            Password = "g6sFUa1q4y",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            DocumentTypeId = 3,
                            Email = "Deborah32@gmail.com",
                            IdentificationNumber = "112883898",
                            LastName = "Champlin",
                            Name = "Joyce",
                            Password = "6r2BfInfr_",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 28,
                            DocumentTypeId = 7,
                            Email = "April_Hand@gmail.com",
                            IdentificationNumber = "499395055",
                            LastName = "Powlowski",
                            Name = "Lesly",
                            Password = "vFbuIsazXo",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 29,
                            DocumentTypeId = 5,
                            Email = "Judson.Terry@yahoo.com",
                            IdentificationNumber = "043469066",
                            LastName = "Shields",
                            Name = "Mason",
                            OauthGoogle = "Nathanael_Larkin",
                            Password = "_X4uBf4Npv",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 30,
                            DocumentTypeId = 2,
                            Email = "Kaela98@gmail.com",
                            IdentificationNumber = "763521622",
                            LastName = "Wisozk",
                            Name = "Ricky",
                            Password = "kt8t3daf__",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 31,
                            DocumentTypeId = 6,
                            Email = "Nikolas.Rodriguez@hotmail.com",
                            IdentificationNumber = "091189302",
                            LastName = "Corwin",
                            Name = "Alfonso",
                            Password = "KYcJH_eqeE",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 32,
                            DocumentTypeId = 5,
                            Email = "Darryl_Runolfsson31@hotmail.com",
                            IdentificationNumber = "537100326",
                            LastName = "Johnson",
                            Name = "Camila",
                            OauthGoogle = "Camila.Paucek",
                            Password = "uufpSK1pMk",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 33,
                            DocumentTypeId = 1,
                            Email = "Werner38@hotmail.com",
                            IdentificationNumber = "828812573",
                            LastName = "Ferry",
                            Name = "Koby",
                            OauthGoogle = "Jordane88",
                            Password = "EUdQuPVhv5",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 34,
                            DocumentTypeId = 4,
                            Email = "Charity_Ritchie@gmail.com",
                            IdentificationNumber = "355017815",
                            LastName = "Weimann",
                            Name = "Elody",
                            OauthGoogle = "Zack.Swaniawski",
                            Password = "arthKLTjPH",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 35,
                            DocumentTypeId = 6,
                            Email = "Kianna.Klein@yahoo.com",
                            IdentificationNumber = "364148867",
                            LastName = "Parisian",
                            Name = "D'angelo",
                            Password = "EDWISZ2O_y",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 36,
                            DocumentTypeId = 6,
                            Email = "Mara5@gmail.com",
                            IdentificationNumber = "007903008",
                            LastName = "Jacobi",
                            Name = "Callie",
                            Password = "MW7nlV7tDq",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 37,
                            DocumentTypeId = 7,
                            Email = "Ambrose.Connelly@hotmail.com",
                            IdentificationNumber = "654395386",
                            LastName = "Jacobi",
                            Name = "Mohammed",
                            OauthGoogle = "Brandy34",
                            Password = "3NNhWFMu_g",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 38,
                            DocumentTypeId = 6,
                            Email = "Madeline98@yahoo.com",
                            IdentificationNumber = "758932601",
                            LastName = "Schmeler",
                            Name = "Vernon",
                            Password = "V5CT4eitjv",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            DocumentTypeId = 3,
                            Email = "Dallas_Hackett@yahoo.com",
                            IdentificationNumber = "832545345",
                            LastName = "Lang",
                            Name = "Aric",
                            Password = "GHpOMsC6PQ",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 40,
                            DocumentTypeId = 5,
                            Email = "Emely77@hotmail.com",
                            IdentificationNumber = "088239488",
                            LastName = "Lubowitz",
                            Name = "Randi",
                            OauthGoogle = "Cristobal.Sipes9",
                            Password = "qO8ztEaxJs",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 41,
                            DocumentTypeId = 1,
                            Email = "Ricky3@hotmail.com",
                            IdentificationNumber = "508629826",
                            LastName = "Koepp",
                            Name = "Jaquelin",
                            OauthGoogle = "Susanna.Reinger",
                            Password = "elQs4XbweA",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 42,
                            DocumentTypeId = 2,
                            Email = "Sadie.Schneider@hotmail.com",
                            IdentificationNumber = "047532376",
                            LastName = "Hamill",
                            Name = "Katelyn",
                            OauthGoogle = "Aglae_Gleichner14",
                            Password = "1ZWHM8q3xO",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 43,
                            DocumentTypeId = 5,
                            Email = "Shanel_Vandervort7@gmail.com",
                            IdentificationNumber = "660946998",
                            LastName = "Schmeler",
                            Name = "Dominique",
                            Password = "nPf2NVkPKA",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 44,
                            DocumentTypeId = 5,
                            Email = "Mario_Stehr@yahoo.com",
                            IdentificationNumber = "866908484",
                            LastName = "Goldner",
                            Name = "Roel",
                            OauthGoogle = "Gerson.Streich86",
                            Password = "fG2ujVPC5q",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            DocumentTypeId = 5,
                            Email = "Amira.Kessler32@gmail.com",
                            IdentificationNumber = "585636099",
                            LastName = "Harris",
                            Name = "Crystel",
                            Password = "TREBMYpBXc",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            DocumentTypeId = 6,
                            Email = "Malinda28@yahoo.com",
                            IdentificationNumber = "626910355",
                            LastName = "Kassulke",
                            Name = "Ruthe",
                            Password = "G5LiUr4IMO",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 47,
                            DocumentTypeId = 7,
                            Email = "Marcelino_Hilll56@gmail.com",
                            IdentificationNumber = "783233892",
                            LastName = "Hayes",
                            Name = "Erick",
                            Password = "9duABNP6nE",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 48,
                            DocumentTypeId = 5,
                            Email = "Bert_Goyette@yahoo.com",
                            IdentificationNumber = "607124687",
                            LastName = "Leannon",
                            Name = "Kelly",
                            Password = "_YAcegLsxO",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            DocumentTypeId = 2,
                            Email = "Raina.Christiansen@hotmail.com",
                            IdentificationNumber = "058055085",
                            LastName = "Gibson",
                            Name = "Garnet",
                            Password = "NHB_D0MtJ3",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 50,
                            DocumentTypeId = 3,
                            Email = "Alexie.Gerhold@yahoo.com",
                            IdentificationNumber = "651958408",
                            LastName = "Moore",
                            Name = "Annamae",
                            OauthGoogle = "Emma.Kuhn54",
                            Password = "R1wyLmbETp",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            DocumentTypeId = 7,
                            Email = "Wyman_Gutmann12@gmail.com",
                            IdentificationNumber = "369712485",
                            LastName = "Wyman",
                            Name = "Nestor",
                            Password = "jrYv5WHLL0",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 52,
                            DocumentTypeId = 6,
                            Email = "Charlie_Olson@hotmail.com",
                            IdentificationNumber = "962732197",
                            LastName = "Schuster",
                            Name = "Chadrick",
                            Password = "TpeF7EHHaU",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 53,
                            DocumentTypeId = 4,
                            Email = "Luis61@gmail.com",
                            IdentificationNumber = "749649700",
                            LastName = "Schaefer",
                            Name = "Boris",
                            Password = "P4mnk3F9Za",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 54,
                            DocumentTypeId = 5,
                            Email = "Jada55@hotmail.com",
                            IdentificationNumber = "212120467",
                            LastName = "Hintz",
                            Name = "Tierra",
                            Password = "xdGmb9C3w5",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 55,
                            DocumentTypeId = 2,
                            Email = "Terrance_Crona@yahoo.com",
                            IdentificationNumber = "143114701",
                            LastName = "Beier",
                            Name = "Newton",
                            OauthGoogle = "Zoila36",
                            Password = "FFTTbqNFv4",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 56,
                            DocumentTypeId = 1,
                            Email = "Susan36@gmail.com",
                            IdentificationNumber = "627331048",
                            LastName = "Hodkiewicz",
                            Name = "Buddy",
                            OauthGoogle = "Elise_Quitzon",
                            Password = "BC7txEiCdX",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 57,
                            DocumentTypeId = 1,
                            Email = "Rahsaan.Zemlak28@gmail.com",
                            IdentificationNumber = "494248255",
                            LastName = "Schroeder",
                            Name = "Lelia",
                            Password = "LHnVl8M8ri",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 58,
                            DocumentTypeId = 7,
                            Email = "Cecile_Weissnat@gmail.com",
                            IdentificationNumber = "330052034",
                            LastName = "Reynolds",
                            Name = "Karley",
                            OauthGoogle = "Abbey_Schroeder80",
                            Password = "psHDJj9_qb",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 59,
                            DocumentTypeId = 4,
                            Email = "Renee21@yahoo.com",
                            IdentificationNumber = "034901132",
                            LastName = "Deckow",
                            Name = "Marcel",
                            OauthGoogle = "Ubaldo.Bartoletti",
                            Password = "TA_GtrcYnu",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 60,
                            DocumentTypeId = 4,
                            Email = "Margot_Grady@hotmail.com",
                            IdentificationNumber = "440883128",
                            LastName = "Larkin",
                            Name = "Millie",
                            OauthGoogle = "Margot.Gutkowski",
                            Password = "X6p_Y88kJA",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 61,
                            DocumentTypeId = 1,
                            Email = "Jarrell.Armstrong31@yahoo.com",
                            IdentificationNumber = "051584955",
                            LastName = "Price",
                            Name = "Gerardo",
                            OauthGoogle = "Sister_Funk70",
                            Password = "grH_tiYWmi",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 62,
                            DocumentTypeId = 2,
                            Email = "Aileen66@hotmail.com",
                            IdentificationNumber = "056529848",
                            LastName = "Nader",
                            Name = "Abby",
                            Password = "QrawAxpJpb",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 63,
                            DocumentTypeId = 7,
                            Email = "Titus.Parisian@gmail.com",
                            IdentificationNumber = "233123545",
                            LastName = "Johnston",
                            Name = "Tod",
                            OauthGoogle = "Abner.Stamm",
                            Password = "1X_yL7xyn8",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 64,
                            DocumentTypeId = 6,
                            Email = "Shea_Mann92@yahoo.com",
                            IdentificationNumber = "214823790",
                            LastName = "Harvey",
                            Name = "Israel",
                            Password = "cfgYom1Mxx",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 65,
                            DocumentTypeId = 5,
                            Email = "Delfina_Emard49@yahoo.com",
                            IdentificationNumber = "673266220",
                            LastName = "Murazik",
                            Name = "Ibrahim",
                            Password = "BySg3KJKPc",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 66,
                            DocumentTypeId = 6,
                            Email = "Amya.Upton4@gmail.com",
                            IdentificationNumber = "995450474",
                            LastName = "McGlynn",
                            Name = "Herman",
                            OauthGoogle = "Franco.Collier82",
                            Password = "ehxPAPBMZX",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 67,
                            DocumentTypeId = 6,
                            Email = "Jazmyn.Morissette@hotmail.com",
                            IdentificationNumber = "089713751",
                            LastName = "Hane",
                            Name = "Aurore",
                            OauthGoogle = "Sammie66",
                            Password = "cpPVNsBBRT",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 68,
                            DocumentTypeId = 5,
                            Email = "Therese71@gmail.com",
                            IdentificationNumber = "670358757",
                            LastName = "Witting",
                            Name = "Terrance",
                            Password = "S5Cm71Hjy7",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 69,
                            DocumentTypeId = 7,
                            Email = "Willard_Jakubowski@hotmail.com",
                            IdentificationNumber = "152208912",
                            LastName = "Schuster",
                            Name = "Tristin",
                            OauthGoogle = "Ole_Lubowitz",
                            Password = "VBllEo91CQ",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 70,
                            DocumentTypeId = 6,
                            Email = "Mose.Bartell30@gmail.com",
                            IdentificationNumber = "203214003",
                            LastName = "Waelchi",
                            Name = "Benjamin",
                            OauthGoogle = "Hellen_Streich",
                            Password = "aS368p0ZcZ",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 71,
                            DocumentTypeId = 3,
                            Email = "Lucas88@yahoo.com",
                            IdentificationNumber = "191531528",
                            LastName = "Moen",
                            Name = "John",
                            OauthGoogle = "Edd_Marquardt",
                            Password = "9hfAphRD3m",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 72,
                            DocumentTypeId = 3,
                            Email = "Paula20@yahoo.com",
                            IdentificationNumber = "857149808",
                            LastName = "Monahan",
                            Name = "Clemens",
                            OauthGoogle = "Kasey89",
                            Password = "8FLG9Jmqak",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 73,
                            DocumentTypeId = 6,
                            Email = "Mabelle_Kreiger50@hotmail.com",
                            IdentificationNumber = "885788510",
                            LastName = "Goyette",
                            Name = "Kyle",
                            Password = "E3PSjZ3qXv",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 74,
                            DocumentTypeId = 2,
                            Email = "Obie9@hotmail.com",
                            IdentificationNumber = "233056209",
                            LastName = "Spencer",
                            Name = "Leone",
                            Password = "KymGsKQGLu",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 75,
                            DocumentTypeId = 6,
                            Email = "Lily_Walker46@gmail.com",
                            IdentificationNumber = "530361650",
                            LastName = "McGlynn",
                            Name = "Dedrick",
                            OauthGoogle = "Edwina.Zieme51",
                            Password = "JdrZDcl551",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 76,
                            DocumentTypeId = 1,
                            Email = "Carmel25@gmail.com",
                            IdentificationNumber = "203449188",
                            LastName = "Fahey",
                            Name = "Elisa",
                            OauthGoogle = "Catharine84",
                            Password = "gVCwz_IYeW",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 77,
                            DocumentTypeId = 6,
                            Email = "Jadyn.Connelly@hotmail.com",
                            IdentificationNumber = "843854242",
                            LastName = "Mann",
                            Name = "Abdullah",
                            OauthGoogle = "Kathlyn_Mayer",
                            Password = "jOSTB1gHyY",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 78,
                            DocumentTypeId = 2,
                            Email = "Camylle_Harris13@yahoo.com",
                            IdentificationNumber = "030475057",
                            LastName = "Predovic",
                            Name = "Fatima",
                            Password = "KQJdEstP0B",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 79,
                            DocumentTypeId = 4,
                            Email = "Nicklaus.Mayer77@gmail.com",
                            IdentificationNumber = "272405406",
                            LastName = "Auer",
                            Name = "Maurice",
                            Password = "j2lLsbwdeR",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 80,
                            DocumentTypeId = 6,
                            Email = "Sibyl_Hoppe48@gmail.com",
                            IdentificationNumber = "425182859",
                            LastName = "Cremin",
                            Name = "Paolo",
                            OauthGoogle = "River_Erdman30",
                            Password = "YVFVdL4_wW",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 81,
                            DocumentTypeId = 2,
                            Email = "Gabrielle.Borer73@hotmail.com",
                            IdentificationNumber = "143535177",
                            LastName = "Weissnat",
                            Name = "Coralie",
                            OauthGoogle = "Antonina.Hilpert56",
                            Password = "F0oJnMveVp",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 82,
                            DocumentTypeId = 4,
                            Email = "Conrad_Gerlach@yahoo.com",
                            IdentificationNumber = "725582179",
                            LastName = "Ankunding",
                            Name = "Candelario",
                            Password = "W6PXlS55Rk",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 83,
                            DocumentTypeId = 3,
                            Email = "Rhiannon_OHara97@yahoo.com",
                            IdentificationNumber = "243232498",
                            LastName = "Maggio",
                            Name = "Jaylen",
                            OauthGoogle = "Bryana_Rath",
                            Password = "zgZ_ISyWq8",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 84,
                            DocumentTypeId = 4,
                            Email = "Ethelyn36@gmail.com",
                            IdentificationNumber = "016029776",
                            LastName = "Koelpin",
                            Name = "Raphaelle",
                            OauthGoogle = "Mya.Champlin",
                            Password = "GSYHD7B_6U",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 85,
                            DocumentTypeId = 7,
                            Email = "Jessyca95@gmail.com",
                            IdentificationNumber = "357199363",
                            LastName = "Gutkowski",
                            Name = "Lydia",
                            OauthGoogle = "Jettie.Dickinson11",
                            Password = "mc_313pdJV",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 86,
                            DocumentTypeId = 7,
                            Email = "Leland30@hotmail.com",
                            IdentificationNumber = "563408795",
                            LastName = "Grimes",
                            Name = "Larry",
                            Password = "pTZShECdRp",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 87,
                            DocumentTypeId = 5,
                            Email = "Piper94@gmail.com",
                            IdentificationNumber = "187472985",
                            LastName = "Fisher",
                            Name = "Aileen",
                            OauthGoogle = "Steve_Altenwerth57",
                            Password = "2h4ovoHHL5",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 88,
                            DocumentTypeId = 5,
                            Email = "Nyah_Beahan91@yahoo.com",
                            IdentificationNumber = "574696984",
                            LastName = "Jakubowski",
                            Name = "Jaeden",
                            Password = "Rdlrj3hG5s",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 89,
                            DocumentTypeId = 6,
                            Email = "Newton13@yahoo.com",
                            IdentificationNumber = "191241238",
                            LastName = "Streich",
                            Name = "Zula",
                            OauthGoogle = "Theodore.Schultz",
                            Password = "MdkaULe4mo",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 90,
                            DocumentTypeId = 4,
                            Email = "Vida.Lehner84@gmail.com",
                            IdentificationNumber = "304042060",
                            LastName = "Casper",
                            Name = "Afton",
                            Password = "OG3rJF70sT",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 91,
                            DocumentTypeId = 4,
                            Email = "Alivia.Bednar@yahoo.com",
                            IdentificationNumber = "548452981",
                            LastName = "Auer",
                            Name = "Luna",
                            OauthGoogle = "Diana70",
                            Password = "24ntqdCY4G",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 92,
                            DocumentTypeId = 3,
                            Email = "Vincenza.Torp@hotmail.com",
                            IdentificationNumber = "721518805",
                            LastName = "Daniel",
                            Name = "Hailee",
                            OauthGoogle = "Janie_Stroman96",
                            Password = "J2E39yJzFS",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 93,
                            DocumentTypeId = 5,
                            Email = "Sharon.Dooley82@hotmail.com",
                            IdentificationNumber = "228759424",
                            LastName = "VonRueden",
                            Name = "Jeff",
                            Password = "Un7fbVktMo",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 94,
                            DocumentTypeId = 2,
                            Email = "Juanita.Konopelski34@yahoo.com",
                            IdentificationNumber = "212669944",
                            LastName = "Mayert",
                            Name = "Minerva",
                            OauthGoogle = "Barton82",
                            Password = "rkcEbnbZ9N",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 95,
                            DocumentTypeId = 1,
                            Email = "Raven_Bartell@gmail.com",
                            IdentificationNumber = "751643117",
                            LastName = "Pfannerstill",
                            Name = "Michel",
                            OauthGoogle = "Porter_Dare3",
                            Password = "8GSPBbWImL",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 96,
                            DocumentTypeId = 7,
                            Email = "Katheryn.Reichert@gmail.com",
                            IdentificationNumber = "067491560",
                            LastName = "Flatley",
                            Name = "Leann",
                            Password = "4UZxJJjwmn",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 97,
                            DocumentTypeId = 7,
                            Email = "Harry.Orn@gmail.com",
                            IdentificationNumber = "733780284",
                            LastName = "Abernathy",
                            Name = "Lonny",
                            Password = "bcSSPRTyCQ",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 98,
                            DocumentTypeId = 5,
                            Email = "Rashawn40@gmail.com",
                            IdentificationNumber = "719815623",
                            LastName = "Streich",
                            Name = "Cale",
                            OauthGoogle = "Hailee50",
                            Password = "MUeINJ9sOX",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 99,
                            DocumentTypeId = 6,
                            Email = "Nora64@hotmail.com",
                            IdentificationNumber = "844686636",
                            LastName = "Fahey",
                            Name = "Mozelle",
                            OauthGoogle = "Francisco95",
                            Password = "dNRi5VH_xV",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 100,
                            DocumentTypeId = 2,
                            Email = "Wilton_Hills@yahoo.com",
                            IdentificationNumber = "371786639",
                            LastName = "Rolfson",
                            Name = "Isac",
                            OauthGoogle = "Moshe_Price91",
                            Password = "0H2rzeKMUF",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int")
                        .HasColumnName("election_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("voters");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.Rol", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Voter", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
