// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurePoll_BE.Data;

#nullable disable

namespace SecurePoll_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908034646_AddTableCandidates")]
    partial class AddTableCandidates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SecurePoll_BE.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int")
                        .HasColumnName("election_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("candidates");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("document_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CC",
                            Name = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "TI",
                            Name = "Tarjeta de Identidad"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PS",
                            Name = "Pasaporte"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "NIT",
                            Name = "Número de Identificación Tributaria"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CE",
                            Name = "Cédula de Extranjería"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "RC",
                            Name = "Registro Civil"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "PEP",
                            Name = "Permiso Especial de Permanencia"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("elections");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Votante"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Candidato"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OauthGoogle")
                        .HasColumnType("longtext")
                        .HasColumnName("oauth_google");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentTypeId = 3,
                            Email = "Chance74@hotmail.com",
                            IdentificationNumber = "700442683",
                            LastName = "Sipes",
                            Name = "Kadin",
                            OauthGoogle = "Claud_Klocko61",
                            Password = "lt2MbrzSZe",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 2,
                            DocumentTypeId = 4,
                            Email = "Malika_Doyle28@hotmail.com",
                            IdentificationNumber = "922344586",
                            LastName = "Johns",
                            Name = "Dena",
                            OauthGoogle = "Ben57",
                            Password = "dc_oTqkAXt",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 3,
                            DocumentTypeId = 1,
                            Email = "Kiana_Hammes@yahoo.com",
                            IdentificationNumber = "843827070",
                            LastName = "Abernathy",
                            Name = "Alan",
                            OauthGoogle = "Opal44",
                            Password = "9i4d_ffBkK",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 4,
                            DocumentTypeId = 2,
                            Email = "Misty.Toy@gmail.com",
                            IdentificationNumber = "698964737",
                            LastName = "Schmeler",
                            Name = "Rhianna",
                            Password = "WRk9AFweAB",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            DocumentTypeId = 5,
                            Email = "Freeman_Kohler6@yahoo.com",
                            IdentificationNumber = "202055940",
                            LastName = "Deckow",
                            Name = "Lizeth",
                            OauthGoogle = "Woodrow.Braun",
                            Password = "DtdxgBDs63",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 6,
                            DocumentTypeId = 2,
                            Email = "Arlo79@yahoo.com",
                            IdentificationNumber = "460474398",
                            LastName = "Harris",
                            Name = "Hassie",
                            OauthGoogle = "Dudley.Veum86",
                            Password = "eKOijp9TgH",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 7,
                            DocumentTypeId = 1,
                            Email = "Emelia_Cole@gmail.com",
                            IdentificationNumber = "449651857",
                            LastName = "Conn",
                            Name = "Mckenzie",
                            Password = "75tKY9EDmR",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            DocumentTypeId = 7,
                            Email = "Rahul_Tremblay5@gmail.com",
                            IdentificationNumber = "281183628",
                            LastName = "Collins",
                            Name = "Haven",
                            Password = "8xAQcYwmbI",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 9,
                            DocumentTypeId = 3,
                            Email = "Tiara_Roberts35@hotmail.com",
                            IdentificationNumber = "055415376",
                            LastName = "Sporer",
                            Name = "Abdul",
                            Password = "i11chJaTOF",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 10,
                            DocumentTypeId = 6,
                            Email = "Leonard55@hotmail.com",
                            IdentificationNumber = "005493632",
                            LastName = "Gerhold",
                            Name = "London",
                            OauthGoogle = "Leonardo58",
                            Password = "IiiiMlfFzy",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 11,
                            DocumentTypeId = 1,
                            Email = "Evan_Kutch@gmail.com",
                            IdentificationNumber = "122500061",
                            LastName = "Schuppe",
                            Name = "Lorenz",
                            OauthGoogle = "Dariana_Strosin",
                            Password = "DwlrBKCEr_",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 12,
                            DocumentTypeId = 2,
                            Email = "Moises61@yahoo.com",
                            IdentificationNumber = "375009676",
                            LastName = "Stark",
                            Name = "Ulises",
                            OauthGoogle = "Luis_Tillman6",
                            Password = "5KnvCeZKQn",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 13,
                            DocumentTypeId = 7,
                            Email = "Dustin.Denesik87@yahoo.com",
                            IdentificationNumber = "780261886",
                            LastName = "Hudson",
                            Name = "Solon",
                            OauthGoogle = "London93",
                            Password = "CCaqj7IIYc",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 14,
                            DocumentTypeId = 1,
                            Email = "Marjory40@yahoo.com",
                            IdentificationNumber = "410029364",
                            LastName = "Jacobs",
                            Name = "Lee",
                            Password = "Yr3DG29fh6",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 15,
                            DocumentTypeId = 1,
                            Email = "Elmore98@yahoo.com",
                            IdentificationNumber = "656503967",
                            LastName = "Reilly",
                            Name = "Domingo",
                            OauthGoogle = "Judah_Pacocha50",
                            Password = "tulNJY6Ymk",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 16,
                            DocumentTypeId = 2,
                            Email = "Fred_Flatley96@yahoo.com",
                            IdentificationNumber = "431129633",
                            LastName = "Stroman",
                            Name = "Makenna",
                            Password = "PNnGup1JWd",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 17,
                            DocumentTypeId = 1,
                            Email = "Ryley.Mosciski3@yahoo.com",
                            IdentificationNumber = "474326099",
                            LastName = "McClure",
                            Name = "Crawford",
                            OauthGoogle = "Zaria.Schroeder",
                            Password = "wGR72EJAv3",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            DocumentTypeId = 3,
                            Email = "Laney_Murphy@gmail.com",
                            IdentificationNumber = "490040884",
                            LastName = "Zboncak",
                            Name = "Wilburn",
                            Password = "tYfHlbLL1B",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 19,
                            DocumentTypeId = 2,
                            Email = "Catalina.Lowe@yahoo.com",
                            IdentificationNumber = "721202850",
                            LastName = "Marks",
                            Name = "Lucile",
                            OauthGoogle = "Liliana59",
                            Password = "JMS4VF9jC2",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 20,
                            DocumentTypeId = 4,
                            Email = "Lonny_Yost10@yahoo.com",
                            IdentificationNumber = "499580598",
                            LastName = "Cruickshank",
                            Name = "Lionel",
                            Password = "B608EBWn1C",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 21,
                            DocumentTypeId = 7,
                            Email = "Jake43@hotmail.com",
                            IdentificationNumber = "698674895",
                            LastName = "Fritsch",
                            Name = "Lois",
                            Password = "sUayLDhZlr",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            DocumentTypeId = 3,
                            Email = "Lia65@gmail.com",
                            IdentificationNumber = "416404615",
                            LastName = "Ziemann",
                            Name = "Roy",
                            Password = "8BIUUTbzPl",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            DocumentTypeId = 4,
                            Email = "Gia_King87@yahoo.com",
                            IdentificationNumber = "965134928",
                            LastName = "Parisian",
                            Name = "Blanca",
                            OauthGoogle = "Brice14",
                            Password = "kXDYJmhtCa",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 24,
                            DocumentTypeId = 5,
                            Email = "Tyrique62@yahoo.com",
                            IdentificationNumber = "479155114",
                            LastName = "McKenzie",
                            Name = "Johnny",
                            Password = "R3stwoTRsG",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 25,
                            DocumentTypeId = 1,
                            Email = "Earnest14@hotmail.com",
                            IdentificationNumber = "979889693",
                            LastName = "Rice",
                            Name = "Anastasia",
                            OauthGoogle = "Mavis.Murray74",
                            Password = "WE7x8ly86z",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 26,
                            DocumentTypeId = 3,
                            Email = "Gene_Mann@hotmail.com",
                            IdentificationNumber = "350314438",
                            LastName = "Nolan",
                            Name = "Jayden",
                            Password = "G8YdUIqahB",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            DocumentTypeId = 2,
                            Email = "Roberto_Beatty@gmail.com",
                            IdentificationNumber = "996452688",
                            LastName = "Bins",
                            Name = "Ernesto",
                            Password = "HDPzCzgR13",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 28,
                            DocumentTypeId = 2,
                            Email = "Carlo.Ankunding@yahoo.com",
                            IdentificationNumber = "952836417",
                            LastName = "Senger",
                            Name = "Timothy",
                            Password = "9jT3xBY7U2",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 29,
                            DocumentTypeId = 3,
                            Email = "Kyla.Mann@yahoo.com",
                            IdentificationNumber = "431671394",
                            LastName = "Mayert",
                            Name = "Enoch",
                            OauthGoogle = "Karlee_Cremin",
                            Password = "cVL0BuOvJq",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 30,
                            DocumentTypeId = 1,
                            Email = "Marcelle_Schuster@yahoo.com",
                            IdentificationNumber = "673476401",
                            LastName = "Sanford",
                            Name = "Syble",
                            OauthGoogle = "Lacey_Doyle",
                            Password = "GsDIfP42tr",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 31,
                            DocumentTypeId = 3,
                            Email = "Mortimer38@yahoo.com",
                            IdentificationNumber = "642079414",
                            LastName = "Rosenbaum",
                            Name = "Elsie",
                            Password = "04X5eFgK2s",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 32,
                            DocumentTypeId = 5,
                            Email = "Nathaniel49@yahoo.com",
                            IdentificationNumber = "765719183",
                            LastName = "Kihn",
                            Name = "Billy",
                            Password = "CB2jP5rixp",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 33,
                            DocumentTypeId = 6,
                            Email = "Cassie.Waters44@yahoo.com",
                            IdentificationNumber = "671753462",
                            LastName = "Reilly",
                            Name = "Maria",
                            OauthGoogle = "Anika_Rempel",
                            Password = "EAYFY5F5S6",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 34,
                            DocumentTypeId = 2,
                            Email = "Graciela.Kulas2@hotmail.com",
                            IdentificationNumber = "599775684",
                            LastName = "Murazik",
                            Name = "Franco",
                            Password = "d6Vv7m73n5",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 35,
                            DocumentTypeId = 5,
                            Email = "May63@hotmail.com",
                            IdentificationNumber = "821793131",
                            LastName = "Hoppe",
                            Name = "Tyrique",
                            OauthGoogle = "Donna.Jacobi",
                            Password = "FqxeFHu3P_",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 36,
                            DocumentTypeId = 7,
                            Email = "Bertram.Krajcik93@yahoo.com",
                            IdentificationNumber = "279831530",
                            LastName = "Gleason",
                            Name = "Belle",
                            OauthGoogle = "Edmond.Sanford",
                            Password = "FzBWQJ9dUn",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 37,
                            DocumentTypeId = 4,
                            Email = "Susanna.Langosh6@gmail.com",
                            IdentificationNumber = "210104785",
                            LastName = "Keeling",
                            Name = "Meta",
                            OauthGoogle = "Tommie79",
                            Password = "NHLEri7YrZ",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 38,
                            DocumentTypeId = 4,
                            Email = "Raheem69@gmail.com",
                            IdentificationNumber = "611758152",
                            LastName = "Legros",
                            Name = "Danyka",
                            Password = "nggJWrTpfB",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 39,
                            DocumentTypeId = 1,
                            Email = "Orville_Kris7@hotmail.com",
                            IdentificationNumber = "218621725",
                            LastName = "Tremblay",
                            Name = "Wiley",
                            Password = "r7Cr6fBJ9y",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 40,
                            DocumentTypeId = 7,
                            Email = "Alanna65@gmail.com",
                            IdentificationNumber = "297952148",
                            LastName = "Carroll",
                            Name = "David",
                            Password = "87IA_zDPcJ",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            DocumentTypeId = 2,
                            Email = "Luisa.Konopelski@yahoo.com",
                            IdentificationNumber = "466810133",
                            LastName = "Heller",
                            Name = "Nayeli",
                            OauthGoogle = "Nico_Skiles42",
                            Password = "hO8xNls_mP",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 42,
                            DocumentTypeId = 3,
                            Email = "Mohammad24@gmail.com",
                            IdentificationNumber = "897417596",
                            LastName = "Hammes",
                            Name = "Stefanie",
                            Password = "WLETRyM4PU",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 43,
                            DocumentTypeId = 5,
                            Email = "Noel10@yahoo.com",
                            IdentificationNumber = "391419118",
                            LastName = "Dare",
                            Name = "Ephraim",
                            Password = "0ACRoRsYnA",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 44,
                            DocumentTypeId = 4,
                            Email = "Milan_Emard@hotmail.com",
                            IdentificationNumber = "351029537",
                            LastName = "Krajcik",
                            Name = "Etha",
                            OauthGoogle = "Marshall.Christiansen90",
                            Password = "vGdmnwMktI",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 45,
                            DocumentTypeId = 1,
                            Email = "Destinee_Goyette@yahoo.com",
                            IdentificationNumber = "130430330",
                            LastName = "Lang",
                            Name = "Constantin",
                            OauthGoogle = "Krystal.Schumm3",
                            Password = "9XL4qwzJF6",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 46,
                            DocumentTypeId = 5,
                            Email = "Mireille_DAmore7@gmail.com",
                            IdentificationNumber = "630463437",
                            LastName = "Gottlieb",
                            Name = "Jayson",
                            Password = "YpepI5rS8f",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 47,
                            DocumentTypeId = 5,
                            Email = "Annetta12@hotmail.com",
                            IdentificationNumber = "511164465",
                            LastName = "Sauer",
                            Name = "Antonina",
                            Password = "gp88GtRVEX",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 48,
                            DocumentTypeId = 5,
                            Email = "Bertram9@yahoo.com",
                            IdentificationNumber = "470474625",
                            LastName = "Schmidt",
                            Name = "Destini",
                            OauthGoogle = "Valentin_Parisian",
                            Password = "VcOQBTvMD7",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            DocumentTypeId = 2,
                            Email = "Audra_Schuster@yahoo.com",
                            IdentificationNumber = "349942922",
                            LastName = "Hills",
                            Name = "Shanna",
                            Password = "i8AoPaFiye",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 50,
                            DocumentTypeId = 2,
                            Email = "Alverta80@yahoo.com",
                            IdentificationNumber = "734904766",
                            LastName = "Wisoky",
                            Name = "Edward",
                            OauthGoogle = "Dave.Cassin61",
                            Password = "QcfA9WyMdA",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 51,
                            DocumentTypeId = 3,
                            Email = "Annie_Sawayn36@hotmail.com",
                            IdentificationNumber = "207304332",
                            LastName = "Beier",
                            Name = "Dejah",
                            OauthGoogle = "Floy_Tromp",
                            Password = "ukj_sP7yIB",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 52,
                            DocumentTypeId = 2,
                            Email = "Ariane_Spinka@gmail.com",
                            IdentificationNumber = "682121109",
                            LastName = "Smith",
                            Name = "Lura",
                            OauthGoogle = "Chelsie.Ward31",
                            Password = "kcoSoPBlRQ",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 53,
                            DocumentTypeId = 5,
                            Email = "Bella_Upton@yahoo.com",
                            IdentificationNumber = "019991836",
                            LastName = "Marquardt",
                            Name = "Johnathan",
                            OauthGoogle = "Osbaldo.Rolfson",
                            Password = "2qpzKGhMnz",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            DocumentTypeId = 4,
                            Email = "Otis_Treutel32@yahoo.com",
                            IdentificationNumber = "952809583",
                            LastName = "Haag",
                            Name = "Alayna",
                            OauthGoogle = "Mose_Schaden41",
                            Password = "tg5FYaPxF5",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 55,
                            DocumentTypeId = 2,
                            Email = "Gloria_Raynor@hotmail.com",
                            IdentificationNumber = "368651725",
                            LastName = "Hagenes",
                            Name = "Jeff",
                            Password = "zkkWOOk3Ts",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 56,
                            DocumentTypeId = 4,
                            Email = "Mitchell.Goldner@hotmail.com",
                            IdentificationNumber = "807106732",
                            LastName = "Goyette",
                            Name = "Marjory",
                            OauthGoogle = "Jeffry_Huels",
                            Password = "pSfg8omLFo",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 57,
                            DocumentTypeId = 6,
                            Email = "Fern_DAmore79@yahoo.com",
                            IdentificationNumber = "012324003",
                            LastName = "Anderson",
                            Name = "Alford",
                            Password = "_7oV6a5Fdo",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 58,
                            DocumentTypeId = 4,
                            Email = "Damaris_Hansen64@yahoo.com",
                            IdentificationNumber = "649572332",
                            LastName = "Mosciski",
                            Name = "Hassie",
                            OauthGoogle = "Webster59",
                            Password = "YjNbQUc1SJ",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 59,
                            DocumentTypeId = 4,
                            Email = "Justen68@gmail.com",
                            IdentificationNumber = "327871687",
                            LastName = "Lehner",
                            Name = "Letitia",
                            OauthGoogle = "Maximilian_Auer12",
                            Password = "d1_0vxHq6W",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 60,
                            DocumentTypeId = 6,
                            Email = "Mauricio.Kiehn10@yahoo.com",
                            IdentificationNumber = "458071754",
                            LastName = "Emard",
                            Name = "Ludwig",
                            Password = "i51ATt4_jo",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 61,
                            DocumentTypeId = 1,
                            Email = "Oliver_Turner@gmail.com",
                            IdentificationNumber = "036163613",
                            LastName = "Halvorson",
                            Name = "Kristofer",
                            Password = "sR6QLvuSVT",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 62,
                            DocumentTypeId = 3,
                            Email = "Madge_Stokes@yahoo.com",
                            IdentificationNumber = "791473909",
                            LastName = "Wehner",
                            Name = "Coby",
                            Password = "kRJHIcL2mv",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 63,
                            DocumentTypeId = 3,
                            Email = "Pansy.Halvorson1@hotmail.com",
                            IdentificationNumber = "544525315",
                            LastName = "Padberg",
                            Name = "Else",
                            Password = "nw6W9CjkuU",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 64,
                            DocumentTypeId = 3,
                            Email = "Frankie56@hotmail.com",
                            IdentificationNumber = "660318405",
                            LastName = "Schoen",
                            Name = "Janessa",
                            Password = "twWMg3gIml",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 65,
                            DocumentTypeId = 2,
                            Email = "Chloe46@hotmail.com",
                            IdentificationNumber = "816245172",
                            LastName = "Nitzsche",
                            Name = "Tessie",
                            OauthGoogle = "Shayna_Crooks39",
                            Password = "9sbnROTFxO",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 66,
                            DocumentTypeId = 7,
                            Email = "Kendrick91@hotmail.com",
                            IdentificationNumber = "597182602",
                            LastName = "Tromp",
                            Name = "Maverick",
                            OauthGoogle = "Carmine_Schuppe",
                            Password = "0LGFNkKQRl",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 67,
                            DocumentTypeId = 1,
                            Email = "Cayla.Walker@gmail.com",
                            IdentificationNumber = "127020157",
                            LastName = "Labadie",
                            Name = "Leopoldo",
                            OauthGoogle = "Jane_McDermott13",
                            Password = "yPmOz8MsES",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 68,
                            DocumentTypeId = 7,
                            Email = "Mara58@yahoo.com",
                            IdentificationNumber = "529068708",
                            LastName = "Collins",
                            Name = "Delphia",
                            OauthGoogle = "Cicero_Wilderman87",
                            Password = "eMyIED2mFd",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 69,
                            DocumentTypeId = 6,
                            Email = "Anahi98@gmail.com",
                            IdentificationNumber = "878704263",
                            LastName = "Shields",
                            Name = "Ruby",
                            OauthGoogle = "Oswaldo.Nikolaus",
                            Password = "bWEe3NxueD",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 70,
                            DocumentTypeId = 6,
                            Email = "Elsa_Blick@yahoo.com",
                            IdentificationNumber = "405318185",
                            LastName = "Reilly",
                            Name = "Owen",
                            OauthGoogle = "Reinhold_Conn",
                            Password = "S0wxgqc3xx",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 71,
                            DocumentTypeId = 6,
                            Email = "Diana.Kuhic90@hotmail.com",
                            IdentificationNumber = "348249903",
                            LastName = "Effertz",
                            Name = "Reina",
                            Password = "yzXBUU8qPR",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 72,
                            DocumentTypeId = 7,
                            Email = "Audra89@hotmail.com",
                            IdentificationNumber = "173519699",
                            LastName = "Parisian",
                            Name = "Nayeli",
                            Password = "i2i4frDvpV",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 73,
                            DocumentTypeId = 4,
                            Email = "Hunter_Hudson@yahoo.com",
                            IdentificationNumber = "192480646",
                            LastName = "Marvin",
                            Name = "Eleonore",
                            Password = "2i7mdwh9YA",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 74,
                            DocumentTypeId = 6,
                            Email = "Bryon_Price40@yahoo.com",
                            IdentificationNumber = "105892468",
                            LastName = "Veum",
                            Name = "Alfred",
                            Password = "pgGmhVCvse",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 75,
                            DocumentTypeId = 5,
                            Email = "Caesar_Toy@gmail.com",
                            IdentificationNumber = "403937676",
                            LastName = "Raynor",
                            Name = "Celine",
                            OauthGoogle = "Arthur_Kuhlman55",
                            Password = "oSOk_nXq2E",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 76,
                            DocumentTypeId = 2,
                            Email = "Pete64@yahoo.com",
                            IdentificationNumber = "775917730",
                            LastName = "Blick",
                            Name = "Garrett",
                            Password = "fqhQQc2jB_",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 77,
                            DocumentTypeId = 3,
                            Email = "Jarrod_Crooks@hotmail.com",
                            IdentificationNumber = "701169099",
                            LastName = "Hyatt",
                            Name = "Madilyn",
                            Password = "Fbqdzr9BNr",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 78,
                            DocumentTypeId = 6,
                            Email = "Mallie.Lemke73@gmail.com",
                            IdentificationNumber = "725952948",
                            LastName = "Johns",
                            Name = "Oral",
                            Password = "D2SyOo_e2R",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 79,
                            DocumentTypeId = 1,
                            Email = "Ilene85@gmail.com",
                            IdentificationNumber = "765288960",
                            LastName = "Grimes",
                            Name = "Presley",
                            OauthGoogle = "Alvera_Haley25",
                            Password = "l8JDSSDbmr",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 80,
                            DocumentTypeId = 7,
                            Email = "Nolan46@gmail.com",
                            IdentificationNumber = "030342516",
                            LastName = "Jerde",
                            Name = "Dee",
                            OauthGoogle = "Lambert_Legros",
                            Password = "1bGf2r1hYY",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 81,
                            DocumentTypeId = 7,
                            Email = "Kendra_Metz@gmail.com",
                            IdentificationNumber = "256640022",
                            LastName = "Renner",
                            Name = "Jessica",
                            Password = "JjBlsMZSmu",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 82,
                            DocumentTypeId = 3,
                            Email = "Garrick.Schmitt@gmail.com",
                            IdentificationNumber = "920192956",
                            LastName = "Gibson",
                            Name = "Karelle",
                            Password = "ydAIoA_WtK",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 83,
                            DocumentTypeId = 4,
                            Email = "Izabella.Hintz7@hotmail.com",
                            IdentificationNumber = "517547330",
                            LastName = "Bins",
                            Name = "Erich",
                            Password = "2rdi3rPjYa",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 84,
                            DocumentTypeId = 3,
                            Email = "Joany.Zboncak28@yahoo.com",
                            IdentificationNumber = "102057892",
                            LastName = "Douglas",
                            Name = "Hector",
                            OauthGoogle = "Cullen.Grimes",
                            Password = "1bLQ_W34V4",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 85,
                            DocumentTypeId = 4,
                            Email = "Gretchen.Cummerata@hotmail.com",
                            IdentificationNumber = "206370644",
                            LastName = "Abbott",
                            Name = "Nicolas",
                            Password = "WHzAFHmpW2",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 86,
                            DocumentTypeId = 7,
                            Email = "Winifred_Mills@hotmail.com",
                            IdentificationNumber = "158075436",
                            LastName = "Bahringer",
                            Name = "Lawrence",
                            OauthGoogle = "Kelvin_Cummings",
                            Password = "X9JaMF346S",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 87,
                            DocumentTypeId = 6,
                            Email = "Keyon96@gmail.com",
                            IdentificationNumber = "495126389",
                            LastName = "Fay",
                            Name = "Bernadette",
                            Password = "pL_gGMUTqV",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 88,
                            DocumentTypeId = 3,
                            Email = "Brando_Lind@gmail.com",
                            IdentificationNumber = "110094625",
                            LastName = "Wilderman",
                            Name = "Maia",
                            Password = "bQkHQIJksF",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 89,
                            DocumentTypeId = 1,
                            Email = "Bonnie41@yahoo.com",
                            IdentificationNumber = "782196124",
                            LastName = "Jacobs",
                            Name = "Marian",
                            OauthGoogle = "Nicolas.Mayert",
                            Password = "W3H_JoZbf6",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 90,
                            DocumentTypeId = 7,
                            Email = "Louisa_Gaylord@yahoo.com",
                            IdentificationNumber = "431167237",
                            LastName = "Reichert",
                            Name = "Alyce",
                            OauthGoogle = "Gussie.OConner36",
                            Password = "xTykfwzn62",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 91,
                            DocumentTypeId = 2,
                            Email = "Hiram_Klocko38@gmail.com",
                            IdentificationNumber = "760087060",
                            LastName = "Runte",
                            Name = "Amira",
                            OauthGoogle = "Linwood.Rohan83",
                            Password = "4axbFypBel",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 92,
                            DocumentTypeId = 6,
                            Email = "Leo_Legros@gmail.com",
                            IdentificationNumber = "634811846",
                            LastName = "Reichel",
                            Name = "Serena",
                            OauthGoogle = "Frankie14",
                            Password = "SGzQPMu_w0",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 93,
                            DocumentTypeId = 1,
                            Email = "Ari_Harber@hotmail.com",
                            IdentificationNumber = "764298108",
                            LastName = "Hodkiewicz",
                            Name = "Zack",
                            Password = "hD4wj9Rp9M",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 94,
                            DocumentTypeId = 6,
                            Email = "Elvis_McKenzie@gmail.com",
                            IdentificationNumber = "647943060",
                            LastName = "Will",
                            Name = "Antonetta",
                            OauthGoogle = "Ansley25",
                            Password = "LMXpe6igCz",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 95,
                            DocumentTypeId = 2,
                            Email = "Drake_Parker84@hotmail.com",
                            IdentificationNumber = "770849342",
                            LastName = "Stehr",
                            Name = "Mark",
                            OauthGoogle = "Abbigail22",
                            Password = "07gOzI51Hl",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 96,
                            DocumentTypeId = 3,
                            Email = "Ivory18@gmail.com",
                            IdentificationNumber = "081370625",
                            LastName = "Rempel",
                            Name = "Wava",
                            OauthGoogle = "Shawn_Conroy",
                            Password = "KSqTsDbjl1",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 97,
                            DocumentTypeId = 4,
                            Email = "Rosalia43@gmail.com",
                            IdentificationNumber = "639610618",
                            LastName = "Legros",
                            Name = "Jade",
                            OauthGoogle = "Abigale_Blick16",
                            Password = "l4sQPNTIdN",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 98,
                            DocumentTypeId = 7,
                            Email = "Rhiannon_Anderson@gmail.com",
                            IdentificationNumber = "016562463",
                            LastName = "Daugherty",
                            Name = "Jessyca",
                            OauthGoogle = "Ladarius.OHara88",
                            Password = "5RSD531Siy",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 99,
                            DocumentTypeId = 6,
                            Email = "Noble_Ullrich@gmail.com",
                            IdentificationNumber = "815394296",
                            LastName = "Greenholt",
                            Name = "Buster",
                            Password = "xIE6LIP5H3",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 100,
                            DocumentTypeId = 7,
                            Email = "Berry5@hotmail.com",
                            IdentificationNumber = "786899412",
                            LastName = "Walter",
                            Name = "Leonora",
                            OauthGoogle = "Elfrieda17",
                            Password = "rOwxKQh0qn",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int")
                        .HasColumnName("election_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("voters");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Candidate", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.Rol", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Voter", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
