// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecurePoll_BE.Data;

#nullable disable

namespace SecurePoll_BE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908132157_AddColumnPublicKeyIntoUsers")]
    partial class AddColumnPublicKeyIntoUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SecurePoll_BE.Models.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int")
                        .HasColumnName("election_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("candidates");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("abbreviation");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("document_types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CC",
                            Name = "Cédula de Ciudadanía"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "TI",
                            Name = "Tarjeta de Identidad"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "PS",
                            Name = "Pasaporte"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "NIT",
                            Name = "Número de Identificación Tributaria"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = "CE",
                            Name = "Cédula de Extranjería"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = "RC",
                            Name = "Registro Civil"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = "PEP",
                            Name = "Permiso Especial de Permanencia"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("start_date");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("elections");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cliente"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Votante"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Candidato"
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int")
                        .HasColumnName("document_type_id");

                    b.Property<string>("Email")
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("identification_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("OauthGoogle")
                        .HasColumnType("longtext")
                        .HasColumnName("oauth_google");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("PublicKey")
                        .HasColumnType("longtext")
                        .HasColumnName("public_key");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id");

                    b.HasIndex("DocumentTypeId");

                    b.HasIndex("RoleId");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DocumentTypeId = 6,
                            Email = "Mollie9@yahoo.com",
                            IdentificationNumber = "006119843",
                            LastName = "Kovacek",
                            Name = "Carolanne",
                            OauthGoogle = "Murray.McLaughlin",
                            Password = "ovH15485q1",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 2,
                            DocumentTypeId = 3,
                            Email = "Elroy.Carter55@yahoo.com",
                            IdentificationNumber = "151483186",
                            LastName = "Emmerich",
                            Name = "Nicola",
                            Password = "iYvkbUOmRp",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 3,
                            DocumentTypeId = 7,
                            Email = "Federico_Hegmann89@yahoo.com",
                            IdentificationNumber = "772124544",
                            LastName = "Gerhold",
                            Name = "Chadrick",
                            OauthGoogle = "Brian.Bergnaum",
                            Password = "qVYKhBaxXE",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 4,
                            DocumentTypeId = 7,
                            Email = "Gerry81@gmail.com",
                            IdentificationNumber = "837488713",
                            LastName = "Prosacco",
                            Name = "Oswald",
                            Password = "J8pRoGjDyA",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 5,
                            DocumentTypeId = 2,
                            Email = "Braden.Block@gmail.com",
                            IdentificationNumber = "742871645",
                            LastName = "Smith",
                            Name = "Jaunita",
                            Password = "lIwiBtfVwp",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 6,
                            DocumentTypeId = 3,
                            Email = "Vallie.Cronin86@gmail.com",
                            IdentificationNumber = "481704408",
                            LastName = "Hirthe",
                            Name = "Godfrey",
                            Password = "FcZwcoa_4f",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 7,
                            DocumentTypeId = 2,
                            Email = "Deondre30@yahoo.com",
                            IdentificationNumber = "823055478",
                            LastName = "Willms",
                            Name = "Merritt",
                            Password = "L1fSPOJi72",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 8,
                            DocumentTypeId = 2,
                            Email = "Evan75@gmail.com",
                            IdentificationNumber = "347685384",
                            LastName = "Carter",
                            Name = "Cedrick",
                            Password = "UYxx8MYH0t",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 9,
                            DocumentTypeId = 6,
                            Email = "Ollie.McLaughlin27@gmail.com",
                            IdentificationNumber = "329796965",
                            LastName = "Wintheiser",
                            Name = "Scottie",
                            OauthGoogle = "Augustus_Crona6",
                            Password = "Uyu0HwXA5h",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 10,
                            DocumentTypeId = 1,
                            Email = "Margarett_McKenzie@hotmail.com",
                            IdentificationNumber = "602404523",
                            LastName = "Leffler",
                            Name = "Aric",
                            Password = "uY6eZSkMyS",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 11,
                            DocumentTypeId = 2,
                            Email = "Damion58@hotmail.com",
                            IdentificationNumber = "144621060",
                            LastName = "Hudson",
                            Name = "Glenda",
                            OauthGoogle = "Mabelle.McGlynn",
                            Password = "cN0LlrPVVL",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 12,
                            DocumentTypeId = 1,
                            Email = "Duane_Walsh14@gmail.com",
                            IdentificationNumber = "733334032",
                            LastName = "Mosciski",
                            Name = "Ryleigh",
                            OauthGoogle = "Clotilde.OKeefe25",
                            Password = "WJTlc7yiTR",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 13,
                            DocumentTypeId = 3,
                            Email = "Rosalia76@gmail.com",
                            IdentificationNumber = "872249698",
                            LastName = "Botsford",
                            Name = "Curt",
                            OauthGoogle = "Delmer65",
                            Password = "qKuxLnWSIb",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 14,
                            DocumentTypeId = 7,
                            Email = "Wiley_Kutch@yahoo.com",
                            IdentificationNumber = "580579397",
                            LastName = "Douglas",
                            Name = "Theron",
                            Password = "ly95JSXZlL",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 15,
                            DocumentTypeId = 7,
                            Email = "Wilhelmine29@hotmail.com",
                            IdentificationNumber = "107558639",
                            LastName = "Douglas",
                            Name = "Adriana",
                            OauthGoogle = "Shemar_Schroeder13",
                            Password = "hKAXi2uOxb",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 16,
                            DocumentTypeId = 2,
                            Email = "Jamey.Terry@gmail.com",
                            IdentificationNumber = "823589710",
                            LastName = "Carter",
                            Name = "Kira",
                            OauthGoogle = "Edmund_Bradtke59",
                            Password = "AoliTaPlzS",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 17,
                            DocumentTypeId = 7,
                            Email = "Braulio_Morar@yahoo.com",
                            IdentificationNumber = "240581431",
                            LastName = "Carter",
                            Name = "Omari",
                            Password = "gTHTUPCfi3",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 18,
                            DocumentTypeId = 7,
                            Email = "Jennyfer_Green@yahoo.com",
                            IdentificationNumber = "598867842",
                            LastName = "Mohr",
                            Name = "Betsy",
                            Password = "dMWtpcgmr3",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 19,
                            DocumentTypeId = 7,
                            Email = "Rolando21@hotmail.com",
                            IdentificationNumber = "366198168",
                            LastName = "Balistreri",
                            Name = "Brenda",
                            OauthGoogle = "Lois.Streich",
                            Password = "DAkx6T1uz9",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 20,
                            DocumentTypeId = 6,
                            Email = "Teagan74@gmail.com",
                            IdentificationNumber = "600487581",
                            LastName = "Koelpin",
                            Name = "Dianna",
                            Password = "ElGtTGTpYb",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 21,
                            DocumentTypeId = 3,
                            Email = "Evangeline_Graham19@yahoo.com",
                            IdentificationNumber = "455038646",
                            LastName = "Bashirian",
                            Name = "Emelia",
                            OauthGoogle = "Shyanne60",
                            Password = "bRIQsA2cCS",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 22,
                            DocumentTypeId = 2,
                            Email = "Tyra_Morissette97@gmail.com",
                            IdentificationNumber = "939381733",
                            LastName = "Grimes",
                            Name = "Jairo",
                            Password = "UIW8CBv_ks",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 23,
                            DocumentTypeId = 6,
                            Email = "Wilburn_Trantow43@hotmail.com",
                            IdentificationNumber = "533707885",
                            LastName = "Murphy",
                            Name = "Nikolas",
                            Password = "mZifCTkAYN",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 24,
                            DocumentTypeId = 1,
                            Email = "Melyssa.Lueilwitz70@yahoo.com",
                            IdentificationNumber = "815460431",
                            LastName = "Koelpin",
                            Name = "Niko",
                            Password = "MFvQYXpsxE",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 25,
                            DocumentTypeId = 3,
                            Email = "Randy_Hessel15@gmail.com",
                            IdentificationNumber = "207044394",
                            LastName = "VonRueden",
                            Name = "Garrison",
                            OauthGoogle = "Kelvin_Deckow",
                            Password = "opRsbRH8Vy",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 26,
                            DocumentTypeId = 6,
                            Email = "Floy.Reichert77@gmail.com",
                            IdentificationNumber = "495508753",
                            LastName = "Bosco",
                            Name = "Cierra",
                            OauthGoogle = "Aracely44",
                            Password = "1V92KwYMI4",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 27,
                            DocumentTypeId = 4,
                            Email = "Burley_Hayes33@hotmail.com",
                            IdentificationNumber = "981330092",
                            LastName = "Schmidt",
                            Name = "Dexter",
                            Password = "DWYNt5PiBe",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 28,
                            DocumentTypeId = 7,
                            Email = "Ali3@yahoo.com",
                            IdentificationNumber = "289482789",
                            LastName = "Hoeger",
                            Name = "Timmothy",
                            Password = "fa23I3pwCi",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 29,
                            DocumentTypeId = 6,
                            Email = "Colin_Mayer47@gmail.com",
                            IdentificationNumber = "688562362",
                            LastName = "Ortiz",
                            Name = "Anabel",
                            Password = "wC1k3DCMvg",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 30,
                            DocumentTypeId = 5,
                            Email = "Chaim_Dickens12@gmail.com",
                            IdentificationNumber = "556654814",
                            LastName = "Feeney",
                            Name = "Devon",
                            OauthGoogle = "Nelle33",
                            Password = "uX4FdBDyrt",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 31,
                            DocumentTypeId = 1,
                            Email = "Oleta65@gmail.com",
                            IdentificationNumber = "839267029",
                            LastName = "Breitenberg",
                            Name = "Peyton",
                            Password = "0dDRN8mCHJ",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 32,
                            DocumentTypeId = 3,
                            Email = "Elyse_Greenfelder76@gmail.com",
                            IdentificationNumber = "199920460",
                            LastName = "Gerlach",
                            Name = "Elyssa",
                            OauthGoogle = "Laverna81",
                            Password = "QiZyiV62hm",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 33,
                            DocumentTypeId = 3,
                            Email = "Jazmin.Ziemann75@yahoo.com",
                            IdentificationNumber = "705723897",
                            LastName = "Daniel",
                            Name = "Gonzalo",
                            Password = "bTAdoJZc0H",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 34,
                            DocumentTypeId = 4,
                            Email = "Beatrice_Predovic52@gmail.com",
                            IdentificationNumber = "506698696",
                            LastName = "O'Connell",
                            Name = "Domenico",
                            Password = "USrwnIDNG8",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 35,
                            DocumentTypeId = 4,
                            Email = "Avis.Prohaska@gmail.com",
                            IdentificationNumber = "411152833",
                            LastName = "Berge",
                            Name = "Amanda",
                            OauthGoogle = "Aron5",
                            Password = "gXSUWsEURL",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 36,
                            DocumentTypeId = 2,
                            Email = "Harley97@gmail.com",
                            IdentificationNumber = "930762299",
                            LastName = "Dickinson",
                            Name = "Aric",
                            Password = "OQGJ3q5UFR",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 37,
                            DocumentTypeId = 6,
                            Email = "Nicholaus_Ortiz@yahoo.com",
                            IdentificationNumber = "675612354",
                            LastName = "Blick",
                            Name = "Charley",
                            OauthGoogle = "Tre26",
                            Password = "QFFtCzjeWh",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 38,
                            DocumentTypeId = 2,
                            Email = "Paolo.Thompson49@gmail.com",
                            IdentificationNumber = "435916801",
                            LastName = "Morissette",
                            Name = "Harvey",
                            OauthGoogle = "Brent.Little65",
                            Password = "lMruwWxe5f",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 39,
                            DocumentTypeId = 7,
                            Email = "Carmella.Kuhic29@hotmail.com",
                            IdentificationNumber = "793199551",
                            LastName = "Roob",
                            Name = "Zakary",
                            OauthGoogle = "Angel.Williamson44",
                            Password = "4DfKh9Viqe",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 40,
                            DocumentTypeId = 2,
                            Email = "Sammie_Cruickshank@gmail.com",
                            IdentificationNumber = "831528561",
                            LastName = "McGlynn",
                            Name = "Berniece",
                            OauthGoogle = "Elbert98",
                            Password = "tqv4jvKsgX",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 41,
                            DocumentTypeId = 6,
                            Email = "Kaci_Hettinger61@yahoo.com",
                            IdentificationNumber = "697241841",
                            LastName = "Funk",
                            Name = "Shanelle",
                            OauthGoogle = "Tamara.Bradtke74",
                            Password = "7AWWVFVEX8",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 42,
                            DocumentTypeId = 6,
                            Email = "Benton24@gmail.com",
                            IdentificationNumber = "572979024",
                            LastName = "O'Conner",
                            Name = "Kenna",
                            Password = "uLUX7nMAtz",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 43,
                            DocumentTypeId = 5,
                            Email = "Emie70@yahoo.com",
                            IdentificationNumber = "620225602",
                            LastName = "Borer",
                            Name = "Rolando",
                            OauthGoogle = "Lila_Daniel97",
                            Password = "It3COQsXMt",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 44,
                            DocumentTypeId = 4,
                            Email = "Adela_Olson61@gmail.com",
                            IdentificationNumber = "246561445",
                            LastName = "Grant",
                            Name = "Quinten",
                            Password = "yNcNcbHyFr",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 45,
                            DocumentTypeId = 7,
                            Email = "Elna_Tremblay14@gmail.com",
                            IdentificationNumber = "505626424",
                            LastName = "Champlin",
                            Name = "Ethel",
                            Password = "85zSintqGM",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 46,
                            DocumentTypeId = 1,
                            Email = "Frederic.Emmerich54@yahoo.com",
                            IdentificationNumber = "182534825",
                            LastName = "Cremin",
                            Name = "Isabel",
                            OauthGoogle = "Marcellus98",
                            Password = "d0dHSZORAW",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 47,
                            DocumentTypeId = 1,
                            Email = "Arianna_Nicolas9@hotmail.com",
                            IdentificationNumber = "561459029",
                            LastName = "Rohan",
                            Name = "Lamont",
                            OauthGoogle = "Lamont17",
                            Password = "XmVJ4nQjiw",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 48,
                            DocumentTypeId = 1,
                            Email = "Ramona.Orn@hotmail.com",
                            IdentificationNumber = "784425047",
                            LastName = "Metz",
                            Name = "Alex",
                            OauthGoogle = "Fiona.Kuhic",
                            Password = "lVT4DIModT",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 49,
                            DocumentTypeId = 2,
                            Email = "Reagan.Yost@hotmail.com",
                            IdentificationNumber = "245952749",
                            LastName = "Macejkovic",
                            Name = "Earl",
                            Password = "REYC7YjMae",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 50,
                            DocumentTypeId = 6,
                            Email = "Jerrell3@hotmail.com",
                            IdentificationNumber = "328985252",
                            LastName = "Bartoletti",
                            Name = "Gillian",
                            Password = "jPj1GeLsZJ",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 51,
                            DocumentTypeId = 1,
                            Email = "Chase_Wintheiser@gmail.com",
                            IdentificationNumber = "408827298",
                            LastName = "Konopelski",
                            Name = "Libby",
                            Password = "b3GkjB7VHn",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 52,
                            DocumentTypeId = 6,
                            Email = "Clementina.Reilly24@hotmail.com",
                            IdentificationNumber = "933626358",
                            LastName = "Bernier",
                            Name = "Benny",
                            OauthGoogle = "Blanca_Grady3",
                            Password = "Ekca7YxHpu",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 53,
                            DocumentTypeId = 1,
                            Email = "Lavern31@hotmail.com",
                            IdentificationNumber = "222121816",
                            LastName = "Reichel",
                            Name = "Fern",
                            Password = "hXORU8Zf_c",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 54,
                            DocumentTypeId = 5,
                            Email = "Jolie.Lakin@gmail.com",
                            IdentificationNumber = "648626731",
                            LastName = "Ruecker",
                            Name = "Amya",
                            Password = "XkMw2m6QOB",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 55,
                            DocumentTypeId = 6,
                            Email = "Cathy_Balistreri13@yahoo.com",
                            IdentificationNumber = "094109433",
                            LastName = "Borer",
                            Name = "Zella",
                            OauthGoogle = "Orpha_Kling",
                            Password = "EqhK4aMWRn",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 56,
                            DocumentTypeId = 3,
                            Email = "Columbus.Kertzmann9@hotmail.com",
                            IdentificationNumber = "735586663",
                            LastName = "Keeling",
                            Name = "Jarrell",
                            Password = "zm607S_LlE",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 57,
                            DocumentTypeId = 1,
                            Email = "Jordyn.Murazik@gmail.com",
                            IdentificationNumber = "533038764",
                            LastName = "Gusikowski",
                            Name = "Alessandro",
                            Password = "L2rOIAcEOB",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 58,
                            DocumentTypeId = 3,
                            Email = "Devon.Quitzon70@gmail.com",
                            IdentificationNumber = "543698773",
                            LastName = "Marquardt",
                            Name = "Jamaal",
                            OauthGoogle = "Arlene.Mayert62",
                            Password = "SFLYlMbe51",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 59,
                            DocumentTypeId = 1,
                            Email = "Mohammad.Schumm26@hotmail.com",
                            IdentificationNumber = "081775615",
                            LastName = "Bogisich",
                            Name = "Keven",
                            Password = "TOpOGRlt9p",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 60,
                            DocumentTypeId = 3,
                            Email = "Joaquin_Treutel@hotmail.com",
                            IdentificationNumber = "012372586",
                            LastName = "Turner",
                            Name = "Immanuel",
                            OauthGoogle = "Vicky52",
                            Password = "J1WMhuDODz",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 61,
                            DocumentTypeId = 3,
                            Email = "Emmie73@hotmail.com",
                            IdentificationNumber = "552727175",
                            LastName = "Kirlin",
                            Name = "Rahsaan",
                            Password = "BeHCVMSDsd",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 62,
                            DocumentTypeId = 2,
                            Email = "Waylon.Kovacek@hotmail.com",
                            IdentificationNumber = "660626700",
                            LastName = "Donnelly",
                            Name = "Omari",
                            Password = "nXfJxTSD_4",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 63,
                            DocumentTypeId = 6,
                            Email = "Shanna.Nicolas@yahoo.com",
                            IdentificationNumber = "555918776",
                            LastName = "Kunze",
                            Name = "Alexandria",
                            OauthGoogle = "Princess_Anderson",
                            Password = "qut_VHLhvk",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 64,
                            DocumentTypeId = 5,
                            Email = "Alena.Schamberger@yahoo.com",
                            IdentificationNumber = "604000636",
                            LastName = "Wolf",
                            Name = "Zachery",
                            OauthGoogle = "Stacy_VonRueden",
                            Password = "X62eQ4wigI",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 65,
                            DocumentTypeId = 5,
                            Email = "Gilda.Cummings32@gmail.com",
                            IdentificationNumber = "871780503",
                            LastName = "McLaughlin",
                            Name = "Haylee",
                            Password = "gmOC1FhQe4",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 66,
                            DocumentTypeId = 4,
                            Email = "Odie49@yahoo.com",
                            IdentificationNumber = "477846751",
                            LastName = "Kerluke",
                            Name = "Tyrel",
                            OauthGoogle = "Quinton79",
                            Password = "dchDoGt_49",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 67,
                            DocumentTypeId = 7,
                            Email = "Sally_Dooley@yahoo.com",
                            IdentificationNumber = "242329691",
                            LastName = "Barton",
                            Name = "Percival",
                            OauthGoogle = "Fiona_Stark",
                            Password = "4Kjj49Ards",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 68,
                            DocumentTypeId = 7,
                            Email = "Clyde.Runte38@yahoo.com",
                            IdentificationNumber = "056472520",
                            LastName = "Ziemann",
                            Name = "Kristy",
                            OauthGoogle = "Isom.Cruickshank70",
                            Password = "vnevTgTc7l",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 69,
                            DocumentTypeId = 5,
                            Email = "Adelle_Funk@gmail.com",
                            IdentificationNumber = "222732840",
                            LastName = "Moen",
                            Name = "Kenneth",
                            Password = "N0KdDSBEN9",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 70,
                            DocumentTypeId = 3,
                            Email = "Madilyn_Abernathy@yahoo.com",
                            IdentificationNumber = "001328381",
                            LastName = "Trantow",
                            Name = "Tessie",
                            OauthGoogle = "Oma_Collins90",
                            Password = "IcAOx1cYmI",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 71,
                            DocumentTypeId = 3,
                            Email = "Evert.Kemmer77@hotmail.com",
                            IdentificationNumber = "673674432",
                            LastName = "Halvorson",
                            Name = "Kim",
                            OauthGoogle = "Hertha_Homenick",
                            Password = "jDSxneMTLx",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 72,
                            DocumentTypeId = 6,
                            Email = "Vivien_Mills@gmail.com",
                            IdentificationNumber = "222118981",
                            LastName = "Schoen",
                            Name = "Denis",
                            Password = "lwAIIbsTrn",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 73,
                            DocumentTypeId = 4,
                            Email = "Karli.Brakus@yahoo.com",
                            IdentificationNumber = "915655407",
                            LastName = "Runolfsson",
                            Name = "Reid",
                            OauthGoogle = "Taylor.Windler",
                            Password = "85KcQONG7T",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 74,
                            DocumentTypeId = 2,
                            Email = "Silas_Nikolaus@yahoo.com",
                            IdentificationNumber = "940897310",
                            LastName = "Kshlerin",
                            Name = "Dariana",
                            OauthGoogle = "Alessandra80",
                            Password = "_zdEptjSsk",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 75,
                            DocumentTypeId = 7,
                            Email = "Adolph_Rogahn@gmail.com",
                            IdentificationNumber = "172134956",
                            LastName = "Paucek",
                            Name = "Amy",
                            Password = "UGn6IYPJ6T",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 76,
                            DocumentTypeId = 3,
                            Email = "Houston.Corwin46@yahoo.com",
                            IdentificationNumber = "405890131",
                            LastName = "Gibson",
                            Name = "Jeremy",
                            Password = "UneLaFNSMD",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 77,
                            DocumentTypeId = 4,
                            Email = "Lawrence_Vandervort@hotmail.com",
                            IdentificationNumber = "562293563",
                            LastName = "Heathcote",
                            Name = "Edythe",
                            OauthGoogle = "Sammy.Metz",
                            Password = "OXLc2M2Onj",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 78,
                            DocumentTypeId = 1,
                            Email = "Theodore_Rosenbaum40@yahoo.com",
                            IdentificationNumber = "366031224",
                            LastName = "Lang",
                            Name = "Marcelle",
                            OauthGoogle = "Keaton_Wolf14",
                            Password = "aJA38X3TMH",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 79,
                            DocumentTypeId = 2,
                            Email = "Dennis81@yahoo.com",
                            IdentificationNumber = "104487749",
                            LastName = "Moen",
                            Name = "Velma",
                            OauthGoogle = "Christa.Watsica",
                            Password = "KdP7cJH22N",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 80,
                            DocumentTypeId = 1,
                            Email = "Karley35@gmail.com",
                            IdentificationNumber = "138681159",
                            LastName = "McLaughlin",
                            Name = "Katarina",
                            OauthGoogle = "Alexanne.Heaney7",
                            Password = "XJJG7PgQLH",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 81,
                            DocumentTypeId = 7,
                            Email = "Betty.Morissette25@hotmail.com",
                            IdentificationNumber = "375024200",
                            LastName = "Muller",
                            Name = "Shayna",
                            Password = "n8C0wmstRF",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 82,
                            DocumentTypeId = 6,
                            Email = "Maddison_Bergstrom21@gmail.com",
                            IdentificationNumber = "191571526",
                            LastName = "Pollich",
                            Name = "Dion",
                            OauthGoogle = "Hulda_Heller88",
                            Password = "KckfEDNoOi",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 83,
                            DocumentTypeId = 7,
                            Email = "Lue.Ritchie@yahoo.com",
                            IdentificationNumber = "700411314",
                            LastName = "Moen",
                            Name = "Burdette",
                            Password = "9gedNwgXmT",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 84,
                            DocumentTypeId = 6,
                            Email = "Amely37@yahoo.com",
                            IdentificationNumber = "795878788",
                            LastName = "Steuber",
                            Name = "Duane",
                            Password = "fL4IRPbKTM",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 85,
                            DocumentTypeId = 3,
                            Email = "Jaclyn81@yahoo.com",
                            IdentificationNumber = "153239440",
                            LastName = "Corkery",
                            Name = "Shyann",
                            Password = "9ERtlEGNmP",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 86,
                            DocumentTypeId = 4,
                            Email = "Enoch.Langworth68@gmail.com",
                            IdentificationNumber = "611686969",
                            LastName = "Blick",
                            Name = "Mose",
                            OauthGoogle = "Tess_Haley",
                            Password = "lAVC2ouBwN",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 87,
                            DocumentTypeId = 3,
                            Email = "Loyal58@yahoo.com",
                            IdentificationNumber = "476810056",
                            LastName = "Erdman",
                            Name = "Harold",
                            OauthGoogle = "Abe76",
                            Password = "S_b9dFumhH",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 88,
                            DocumentTypeId = 1,
                            Email = "Madalyn27@yahoo.com",
                            IdentificationNumber = "248830194",
                            LastName = "Bailey",
                            Name = "Waldo",
                            Password = "2Ve81t_Vhi",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 89,
                            DocumentTypeId = 4,
                            Email = "Alden76@yahoo.com",
                            IdentificationNumber = "960814530",
                            LastName = "McCullough",
                            Name = "Kane",
                            Password = "HO6htcdaVU",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 90,
                            DocumentTypeId = 1,
                            Email = "Rasheed.Schuster@gmail.com",
                            IdentificationNumber = "978723986",
                            LastName = "Huel",
                            Name = "Heather",
                            Password = "IQV4NkXjdu",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 91,
                            DocumentTypeId = 1,
                            Email = "Amira64@gmail.com",
                            IdentificationNumber = "286134027",
                            LastName = "Tillman",
                            Name = "Doyle",
                            Password = "D5BIqC6QOI",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 92,
                            DocumentTypeId = 2,
                            Email = "Jovan25@yahoo.com",
                            IdentificationNumber = "972713542",
                            LastName = "Upton",
                            Name = "Eveline",
                            OauthGoogle = "Jazlyn.Nader43",
                            Password = "XLJ72MBzxr",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 93,
                            DocumentTypeId = 6,
                            Email = "Prince_Toy95@hotmail.com",
                            IdentificationNumber = "786512360",
                            LastName = "Satterfield",
                            Name = "Brennan",
                            Password = "AOhL7Quzbb",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 94,
                            DocumentTypeId = 3,
                            Email = "Rahul_West@yahoo.com",
                            IdentificationNumber = "470757764",
                            LastName = "Bernier",
                            Name = "Angelica",
                            Password = "BuxB5jgXV7",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 95,
                            DocumentTypeId = 6,
                            Email = "Krista_Kulas2@yahoo.com",
                            IdentificationNumber = "486664994",
                            LastName = "Quigley",
                            Name = "Joan",
                            OauthGoogle = "Coleman_Casper",
                            Password = "Yra06HzIlj",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 96,
                            DocumentTypeId = 2,
                            Email = "Kaleb.Miller88@yahoo.com",
                            IdentificationNumber = "993140100",
                            LastName = "Haag",
                            Name = "Hans",
                            Password = "PF8wEJ3EGG",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 97,
                            DocumentTypeId = 7,
                            Email = "Alex_Kohler@yahoo.com",
                            IdentificationNumber = "831482405",
                            LastName = "Rippin",
                            Name = "Casimer",
                            Password = "4DGLjuoPDs",
                            RoleId = 3
                        },
                        new
                        {
                            Id = 98,
                            DocumentTypeId = 1,
                            Email = "Ebony.Bartoletti@yahoo.com",
                            IdentificationNumber = "818048707",
                            LastName = "Schmitt",
                            Name = "Nettie",
                            OauthGoogle = "Maddison.Walsh18",
                            Password = "Hs3ymt5ZQc",
                            RoleId = 4
                        },
                        new
                        {
                            Id = 99,
                            DocumentTypeId = 2,
                            Email = "Monique43@yahoo.com",
                            IdentificationNumber = "261637489",
                            LastName = "Wiza",
                            Name = "Otto",
                            Password = "tWjHcD1G_6",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 100,
                            DocumentTypeId = 4,
                            Email = "Jewel_Bins59@hotmail.com",
                            IdentificationNumber = "285155562",
                            LastName = "Strosin",
                            Name = "Lance",
                            Password = "aYuIrN_Tay",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Voter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ElectionId")
                        .HasColumnType("int")
                        .HasColumnName("election_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ElectionId");

                    b.HasIndex("UserId");

                    b.ToTable("voters");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Candidate", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Election", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.User", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.DocumentType", "DocumentType")
                        .WithMany()
                        .HasForeignKey("DocumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.Rol", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SecurePoll_BE.Models.Voter", b =>
                {
                    b.HasOne("SecurePoll_BE.Models.Election", "Election")
                        .WithMany()
                        .HasForeignKey("ElectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SecurePoll_BE.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Election");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
